import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { ScrollView, StyleSheet, Text, View, Pressable } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { tokenSchema } from '@/api/schema';
import { compactUsd, signedPercent, tokenPrice } from '@/lib/format';
import { colors, spacing } from '@/theme';

export default function TokenDetail() {
  const router = useRouter(); const { address, snapshot } = useLocalSearchParams<{ address: string; snapshot?: string }>();
  let parsed: unknown; try { parsed = snapshot ? JSON.parse(snapshot) : null; } catch { parsed = null; } const result = tokenSchema.safeParse(parsed); const token = result.success ? result.data : null;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={20} color={colors.text} /></Pressable><Text style={styles.address} numberOfLines={1}>{address}</Text></View>{token ? <><Text style={styles.symbol}>{token.symbol}</Text><Text style={styles.name}>{token.name} · {token.dex}</Text><Text style={styles.price}>{tokenPrice(token.price)}</Text><Text style={[styles.change, { color: token.change24h >= 0 ? colors.positive : colors.negative }]}>{signedPercent(token.change24h)} · 24h</Text><View style={styles.grid}><Metric label="Market cap" value={compactUsd(token.marketCap)} /><Metric label="Liquidity" value={compactUsd(token.liquidity)} /><Metric label="24h volume" value={compactUsd(token.volume24h)} /><Metric label="Holders" value={token.holderCount?.toLocaleString() ?? '—'} /></View><View style={styles.notice}><Ionicons name="shield-checkmark" color={colors.warning} size={18} /><Text style={styles.noticeText}>Trading is unavailable in this slice. Execution will require authenticated wallet ownership, quote validation, simulation, explicit confirmation, and server-side policy gates.</Text></View></> : <View style={styles.empty}><Text style={styles.emptyTitle}>Snapshot unavailable</Text><Text style={styles.name}>Return to Discover and select this token again.</Text></View>}</ScrollView></SafeAreaView>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg }, top: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, back: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface }, address: { flex: 1, color: colors.muted, fontSize: 11 }, symbol: { color: colors.text, fontSize: 38, fontWeight: '900', marginTop: 40 }, name: { color: colors.muted, marginTop: 4 }, price: { color: colors.text, fontSize: 30, fontWeight: '800', marginTop: spacing.xl }, change: { fontWeight: '800', marginTop: spacing.sm }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, marginTop: 32 }, metric: { width: '47%', padding: spacing.lg, borderRadius: 14, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, metricLabel: { color: colors.muted, fontSize: 11 }, metricValue: { color: colors.text, fontSize: 17, fontWeight: '800', marginTop: 8 }, notice: { flexDirection: 'row', gap: spacing.md, padding: spacing.lg, borderRadius: 14, backgroundColor: '#2d2715', marginTop: spacing.xl }, noticeText: { flex: 1, color: colors.warning, fontSize: 11, lineHeight: 17 }, empty: { alignItems: 'center', paddingTop: 100 }, emptyTitle: { color: colors.text, fontSize: 18, fontWeight: '800' } });
