import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { usePrivyIdentity } from '@/auth/PrivyAuthProvider';
import { validEmail } from '@/auth/context';
import { colors, spacing } from '@/theme';

export default function AuthScreen() {
  const auth = usePrivyIdentity();
  const router = useRouter();
  const [email, setEmail] = useState('');
  const [code, setCode] = useState('');
  const [codeSent, setCodeSent] = useState(false);
  if (auth.authenticated) return <SafeAreaView style={styles.safe}><View style={styles.center}><Ionicons name="shield-checkmark" size={42} color={colors.accent} /><Text accessibilityRole="header" style={styles.title}>Signed in securely</Text><Text style={styles.hint}>{auth.userLabel ?? 'Privy account'}</Text><Pressable accessibilityRole="button" accessibilityLabel="Continue to Terminal DEX" onPress={() => router.replace('/(tabs)/portfolio')} style={styles.primary}><Text style={styles.primaryText}>Continue</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Sign out of Privy" onPress={() => void auth.logout()} style={styles.secondary}><Text style={styles.secondaryText}>Sign out</Text></Pressable></View></SafeAreaView>;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Pressable accessibilityRole="button" accessibilityLabel="Close login" onPress={() => router.back()} style={styles.close}><Ionicons name="close" size={24} color={colors.text} /></Pressable><Text style={styles.eyebrow}>TERMINAL DEX · PRIVY</Text><Text accessibilityRole="header" style={styles.title}>Sign up or sign in</Text><Text style={styles.hint}>Use the same Privy identity as Terminal DEX Web. Authentication does not enable trading, signing, or transaction submission.</Text>{!auth.configured ? <View accessibilityRole="alert" style={styles.notice}><Text style={styles.noticeText}>Privy is not configured for this build. Set EXPO_PUBLIC_PRIVY_APP_ID and EXPO_PUBLIC_PRIVY_CLIENT_ID, then create a new development build.</Text></View> : !auth.ready ? <ActivityIndicator accessibilityLabel="Initializing Privy" color={colors.accent} /> : <>{auth.supportsEmailOtp ? <View style={styles.card}><Text style={styles.label}>Email</Text><TextInput accessibilityLabel="Privy email address" value={email} onChangeText={setEmail} inputMode="email" autoCapitalize="none" autoCorrect={false} placeholder="you@example.com" placeholderTextColor={colors.muted} style={styles.input} />{codeSent ? <><Text style={styles.label}>Verification code</Text><TextInput accessibilityLabel="Privy verification code" value={code} onChangeText={(value) => setCode(value.replace(/\D/g, '').slice(0, 8))} inputMode="numeric" autoComplete="one-time-code" placeholder="123456" placeholderTextColor={colors.muted} style={styles.input} /><Button label="Verify and continue" busy={auth.busy} disabled={code.length < 4} onPress={() => void auth.verifyEmailCode(email, code)} /><Pressable accessibilityRole="button" accessibilityLabel="Use another email" onPress={() => { setCodeSent(false); setCode(''); }} style={styles.textButton}><Text style={styles.link}>Use another email</Text></Pressable></> : <Button label="Continue with email" busy={auth.busy} disabled={!validEmail(email)} onPress={async () => { if (await auth.sendEmailCode(email)) setCodeSent(true); }} />}</View> : <Button label="Open secure Privy login" busy={auth.busy} onPress={auth.openLogin} />}<View style={styles.divider}><View style={styles.line} /><Text style={styles.dividerText}>OR</Text><View style={styles.line} /></View><Button label="Continue with Google" busy={auth.busy} onPress={() => void auth.loginWithGoogle()} secondary />{auth.error ? <Text accessibilityRole="alert" style={styles.error}>{auth.error}</Text> : null}</>}</ScrollView></SafeAreaView>;
}

function Button({ label, busy, disabled, secondary, onPress }: { label: string; busy: boolean; disabled?: boolean; secondary?: boolean; onPress: () => void }) { const unavailable = busy || disabled; return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ disabled: unavailable, busy }} disabled={unavailable} onPress={onPress} style={[styles.primary, secondary && styles.secondary, unavailable && styles.disabled]}>{busy ? <ActivityIndicator color={secondary ? colors.accent : colors.background} /> : <Text style={secondary ? styles.secondaryText : styles.primaryText}>{label}</Text>}</Pressable>; }

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, content: { flexGrow: 1, padding: spacing.xl, justifyContent: 'center' }, center: { flex: 1, padding: spacing.xl, justifyContent: 'center', alignItems: 'center' }, close: { position: 'absolute', top: spacing.lg, right: spacing.lg, width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, eyebrow: { color: colors.accent, fontSize: 10, fontWeight: '900', letterSpacing: 2 }, title: { color: colors.text, fontSize: 28, fontWeight: '900', marginTop: spacing.sm, textAlign: 'center' }, hint: { color: colors.muted, fontSize: 12, lineHeight: 19, marginVertical: spacing.lg, textAlign: 'center' }, card: { gap: spacing.sm }, label: { color: colors.text, fontSize: 11, fontWeight: '800', marginTop: spacing.sm }, input: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: 11, paddingHorizontal: spacing.md, color: colors.text, backgroundColor: colors.surface }, primary: { minHeight: 48, marginTop: spacing.md, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.accent, paddingHorizontal: spacing.lg }, primaryText: { color: colors.background, fontWeight: '900' }, secondary: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.accent }, secondaryText: { color: colors.accent, fontWeight: '900' }, disabled: { opacity: 0.45 }, divider: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginTop: spacing.lg }, line: { height: StyleSheet.hairlineWidth, backgroundColor: colors.border, flex: 1 }, dividerText: { color: colors.muted, fontSize: 9, fontWeight: '900' }, textButton: { minHeight: 44, justifyContent: 'center', alignItems: 'center' }, link: { color: colors.accent, fontWeight: '800' }, error: { color: colors.negative, textAlign: 'center', marginTop: spacing.lg }, notice: { padding: spacing.lg, borderRadius: 12, backgroundColor: '#2d2715', borderWidth: 1, borderColor: colors.warning }, noticeText: { color: colors.warning, lineHeight: 19 }, });
