import { Ionicons } from '@expo/vector-icons';
import { useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useWalletSession } from '@/security/WalletSessionProvider';
import { clearLocalAppData } from '@/settings/privacy';
import { useSettings, type Language } from '@/settings/SettingsProvider';
import { colors, spacing } from '@/theme';

export default function SettingsScreen() {
  const router = useRouter(); const queryClient = useQueryClient(); const wallet = useWalletSession(); const settings = useSettings(); const [clearing, setClearing] = useState(false);
  const clear = async () => { setClearing(true); try { await wallet.disconnect(); await clearLocalAppData(); await settings.resetPreferences(); queryClient.clear(); } finally { setClearing(false); } };
  const confirmClear = () => Alert.alert('Clear private and local data?', 'This disconnects the wallet, revokes the app session, removes watch-only addresses, watchlists, filters, and preferences. Server-owned records are not deleted.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Clear local data', style: 'destructive', onPress: () => void clear() }]);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Back from Settings" onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={18} color={colors.text} /></Pressable><View><Text style={styles.eyebrow}>DEVICE CONTROLS</Text><Text style={styles.title}>{settings.t('settings')}</Text></View></View>
    <Section title="Language / Ngôn ngữ" description="Navigation labels update immediately. Market symbols and provider evidence remain untranslated to preserve exact meaning."><View style={styles.segment}>{(['en', 'vi'] as Language[]).map((value) => <Pressable accessibilityRole="radio" accessibilityState={{ checked: settings.language === value }} key={value} onPress={() => settings.setLanguage(value)} style={[styles.segmentItem, settings.language === value && styles.active]}><Text style={[styles.segmentText, settings.language === value && styles.activeText]}>{value === 'en' ? 'English' : 'Tiếng Việt'}</Text></Pressable>)}</View></Section>
    <Section title="Accessibility" description="Terminal DEX respects the operating system font scale and screen reader. Controls expose roles, state, and labels."><SettingRow label="Reduce motion" detail="Disables optional motion; live market refresh remains enabled." value={settings.reduceMotion} onChange={settings.setReduceMotion} /></Section>
    <Section title={settings.t('privacySecurity')} description="Diagnostic telemetry is disabled by default. If enabled later, bounded payloads pass credential, signature, and address redaction before transport."><SettingRow label="Diagnostic telemetry" detail="No telemetry transport is configured in this build." value={settings.diagnosticTelemetry} onChange={settings.setDiagnosticTelemetry} /><Evidence icon="lock-closed" text="Production API traffic requires HTTPS. iOS arbitrary loads and Android cleartext traffic are disabled." /><Evidence icon="link" text="Deep-link token addresses must decode to exactly 32 bytes; embedded snapshots are capped at 12 KB and must match the route." /><Evidence icon="finger-print" text="Verified wallet metadata stays in device-only secure storage and re-locks after backgrounding." /></Section>
    <Section title="Data controls" description="Reset affects this installation only. Durable alerts, CopyTrade strategies, and other server-owned data require their own authenticated deletion flows."><Pressable accessibilityRole="button" accessibilityLabel="Clear local app data" disabled={clearing} onPress={confirmClear} style={styles.destructive}><Ionicons name="trash" size={15} color={colors.negative} /><Text style={styles.destructiveText}>{clearing ? 'Clearing…' : 'Disconnect and clear local data'}</Text></Pressable></Section>
    <Text style={styles.footer}>Terminal DEX Mobile 0.1.0 · non-custodial · no secret keys stored</Text>
  </ScrollView></SafeAreaView>;
}
function Section({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text><Text style={styles.description}>{description}</Text>{children}</View>; }
function SettingRow({ label, detail, value, onChange }: { label: string; detail: string; value: boolean; onChange: (value: boolean) => Promise<void> }) { return <View style={styles.row}><View style={styles.flex}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowDetail}>{detail}</Text></View><Switch accessibilityLabel={label} value={value} onValueChange={(next) => void onChange(next)} trackColor={{ false: colors.border, true: colors.accentDim }} thumbColor={value ? colors.accent : colors.muted} /></View>; }
function Evidence({ icon, text }: { icon: keyof typeof Ionicons.glyphMap; text: string }) { return <View style={styles.evidence}><Ionicons name={icon} size={15} color={colors.accent} /><Text style={styles.evidenceText}>{text}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingBottom: 70 }, header: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginBottom: spacing.xl }, back: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: 10 }, eyebrow: { color: colors.accent, fontSize: 9, fontWeight: '900', letterSpacing: 1.7 }, title: { color: colors.text, fontSize: 25, fontWeight: '900' }, section: { marginBottom: spacing.md, padding: spacing.lg, borderWidth: 1, borderColor: colors.border, borderRadius: 14, backgroundColor: colors.surface }, sectionTitle: { color: colors.text, fontSize: 14, fontWeight: '900' }, description: { color: colors.muted, fontSize: 9, lineHeight: 14, marginTop: 5, marginBottom: spacing.md }, segment: { flexDirection: 'row', padding: 4, borderRadius: 10, backgroundColor: colors.background }, segmentItem: { flex: 1, alignItems: 'center', padding: 9, borderRadius: 8 }, active: { backgroundColor: colors.accent }, segmentText: { color: colors.muted, fontSize: 10, fontWeight: '800' }, activeText: { color: colors.background }, row: { minHeight: 55, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border }, flex: { flex: 1 }, rowLabel: { color: colors.text, fontSize: 11, fontWeight: '800' }, rowDetail: { color: colors.muted, fontSize: 8, lineHeight: 13, marginTop: 3 }, evidence: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm, paddingVertical: spacing.sm, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border }, evidenceText: { flex: 1, color: colors.muted, fontSize: 9, lineHeight: 14 }, destructive: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm, padding: 12, borderWidth: 1, borderColor: '#5a2630', borderRadius: 10, backgroundColor: '#211217' }, destructiveText: { color: colors.negative, fontSize: 10, fontWeight: '900' }, footer: { color: colors.muted, textAlign: 'center', fontSize: 8, marginTop: spacing.lg } });
