import AsyncStorage from "@react-native-async-storage/async-storage";
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type Language = "en" | "vi";
type Settings = {
  language: Language;
  reduceMotion: boolean;
  diagnosticTelemetry: boolean;
};
type SettingsContext = Settings & {
  ready: boolean;
  setLanguage: (value: Language) => Promise<void>;
  setReduceMotion: (value: boolean) => Promise<void>;
  setDiagnosticTelemetry: (value: boolean) => Promise<void>;
  resetPreferences: () => Promise<void>;
  t: (key: TranslationKey, values?: Record<string, string | number>) => string;
};
const KEY = "terminal-dex:settings:v1";
const defaults: Settings = {
  language: "en",
  reduceMotion: false,
  diagnosticTelemetry: false,
};
const en = {
  discover: "Discover",
  trenches: "Trenches",
  monitor: "Monitor",
  portfolio: "Portfolio",
  more: "More",
  moreTools: "More tools",
  settings: "Settings",
  privacySecurity: "Privacy & security",
  privacyAccessibilityLanguages: "PRIVACY · A11Y · VI/EN",
  track: "Track",
  readOnlyTracking: "READ-ONLY TRACKING",
  refreshTrack: "Refresh tracking evidence",
  trackBoundary:
    "Observed provider and indexed events only. Track does not follow wallets, subscribe to social channels, dispatch alerts, or execute transactions from this device.",
  selectTrackFilter: "Select Track filter {filter}",
  trackFilter_all: "All",
  trackFilter_wallet: "Wallet",
  trackFilter_kol: "KOL",
  trackFilter_social: "X / TG",
  loadingTrack: "Loading tracking evidence…",
  trackUnavailable: "Tracking evidence unavailable.",
  sourceStatus: "SOURCE STATUS",
  launchPools: "Launch pools",
  whaleTransactions: "Whale transactions",
  observedEventHistory: "OBSERVED EVENT HISTORY",
  socialTrackUnavailable:
    "X/TG source events are not exposed by an authoritative mobile-safe contract. Social-only observations remain unavailable and are not inferred from market activity.",
  noTrackEvents: "No matching observed events.",
  trackCursorBoundary:
    "The backend returns one bounded deduplicated observation window without a cursor. Older history and continuous tracking are unavailable.",
  deliveryEvidence: "DURABLE DELIVERY EVIDENCE",
  verifyForDeliveryEvidence:
    "Verify wallet ownership to read the owner-scoped delivery ledger.",
  unlockForDeliveryEvidence:
    "Unlock the verified wallet session to read delivery evidence.",
  deliveryUnavailable: "Delivery evidence unavailable.",
  noDeliveryEvidence: "No durable delivery records for this owner.",
  openTrackEvent: "Open {symbol} {type} tracking evidence",
  dedupeId: "dedupe {id}",
  retryTrack: "Retry tracking evidence",
  copyTrade: "CopyTrade",
  topTraders: "Top Traders",
  claimMonitor: "Claim Monitor",
  openToolStatus: "{tool} {status}",
  realData: "REAL DATA",
  searchTokens: "Search live tokens or mint",
  clearSearch: "Clear token search",
  trending: "Trending",
  gainers: "Gainers",
  losers: "Losers",
  volume: "Volume",
  newPairs: "New Pairs",
  hotSearches: "Hot Searches",
  surge: "Surge",
  pumpLive: "Pump Live",
  watchlist: "Watchlist",
  filter: "Filter",
  openFilters: "Open market filters",
  searching: "Searching",
  marketFeed: "Market feed",
  searchingSources: "Searching real market sources…",
  loadingMarkets: "Loading live markets…",
  loadingMoreMarkets: "Loading more market evidence…",
  marketUnavailable: "Market data unavailable",
  retry: "Retry",
  watchlistEmpty: "Your watchlist is empty",
  noMatchingTokens: "No matching tokens",
  watchlistHint: "Star tokens from any Discovery list to keep them here.",
  filtersHint: "Adjust filters, search, or choose another market window.",
  marketFilters: "Market filters",
  closeFilters: "Close market filters",
  all: "All",
  minLiquidity: "Minimum liquidity (USD)",
  minMarketCap: "Minimum market cap (USD)",
  reset: "Reset",
  applyFilters: "Apply filters",
  selectMode: "Select {mode} market list",
  selectPeriod: "Select {period} market period",
  selectDex: "Select {dex} DEX",
  nextBc: "NextBC",
  offlineBanner:
    "Offline · showing only already loaded evidence. Requests and automatic refresh are paused.",
  recoveredBanner: "Connection restored · refreshing active evidence.",
  liveLaunches: "LIVE LAUNCHES",
  new: "New",
  almostBonded: "Almost bonded",
  migrated: "Migrated",
  source: "Source",
  loading: "loading",
  launchFeed: "provider-backed launch feed",
  loadingLaunches: "Loading real launch feeds…",
  noLaunches: "No verified {lane} tokens are available.",
  openTrenchFilters: "Open launch filters",
  trenchMatches: "{shown} of {total} launches",
  noTrenchMatches: "No launches match the active filters.",
  trenchKeyword: "Symbol, name, or token address",
  selectLaunchpad: "Select launchpad {launchpad}",
  minVolume24h: "Min 24h volume",
  maxAgeMinutes: "Max age (minutes)",
  minBondingProgress: "Min bonding (%)",
  openLaunch: "Open {symbol} launch details",
  reviewQuoteLabel: "Review {symbol} quote",
  bondingProgress: "Bonding progress",
  marketCap: "MCap",
  liquidity: "Liquidity",
  hourVolume: "1h volume",
  buysSells: "5m B/S",
  reviewQuote: "Review quote",
  unknown: "unknown",
  unavailable: "unavailable",
  routesNote:
    "Routes activate only after their real contracts and security checks are implemented.",
  openSettings: "Open Settings",
  intelligenceAutomation: "INTELLIGENCE & AUTOMATION",
  automationWarning:
    "CopyTrade saves paused strategies. AI recommendations remain advisory and paper-only.",
  available: "available",
  queued: "queued",
  open: "OPEN",
  deviceControls: "DEVICE CONTROLS",
  backSettings: "Back from Settings",
  language: "Language / Ngôn ngữ",
  languageDescription:
    "All primary tabs update immediately. Market symbols and provider evidence remain untranslated to preserve exact meaning.",
  accessibility: "Accessibility",
  accessibilityDescription:
    "Terminal DEX respects operating-system font scaling and screen readers. Controls expose roles, state, labels, and selected or disabled status.",
  reduceMotion: "Reduce motion",
  reduceMotionDetail:
    "Disables optional motion; live market refresh remains enabled.",
  telemetryDescription:
    "Diagnostic telemetry is disabled by default. If enabled later, bounded payloads pass credential, signature, and address redaction before transport.",
  diagnosticTelemetry: "Diagnostic telemetry",
  noTelemetry: "No telemetry transport is configured in this build.",
  transportSecurity:
    "Production API traffic requires HTTPS. iOS arbitrary loads and Android cleartext traffic are disabled.",
  deepLinkSecurity:
    "Deep-link token addresses must decode to exactly 32 bytes; embedded snapshots are capped at 12 KB and must match the route.",
  walletSecurity:
    "Verified wallet metadata stays in device-only secure storage and re-locks after backgrounding.",
  dataControls: "Data controls",
  dataControlsDescription:
    "Reset affects this installation only. Durable alerts, CopyTrade strategies, and other server-owned data require their own authenticated deletion flows.",
  clearQuestion: "Clear private and local data?",
  clearDescription:
    "This disconnects the wallet, revokes the app session, and removes local addresses, watchlists, filters, research, and preferences. Server-owned records are not deleted.",
  cancel: "Cancel",
  clearLocalData: "Clear local data",
  clearing: "Clearing…",
  disconnectClear: "Disconnect and clear local data",
  clearComplete: "Wallet disconnected and local app data cleared.",
  clearFailed:
    "Could not finish clearing all local data. Review device state and retry.",
  footerSecurity:
    "Terminal DEX Mobile 0.1.0 · non-custodial · no secret keys stored",
  observationDesk: "OBSERVATION DESK",
  live: "Live",
  rules: "Rules",
  delivery: "Delivery",
  connecting: "CONNECTING",
  selectMonitorView: "Select {view} monitor view",
  loadingActivity: "Loading observed Solana activity…",
  noActivity:
    "No indexed on-chain observations are currently available. This feed does not synthesize activity.",
  signedObservations: "{count} signed observations · refresh 30s",
  openMonitorToken: "Open {symbol} details",
  loadingRules: "Loading database-backed rules…",
  alertRules: "Alert rules",
  rulesSchedulerBoundary:
    "Evaluated by the backend scheduler; mobile does not claim background execution.",
  createAlertRule: "Create alert rule",
  close: "Close",
  newRule: "New rule",
  noAlertRules:
    "No persisted alert rules yet. Create one after verifying wallet ownership.",
  ruleName: "RULE NAME",
  alertName: "Alert name",
  alertNamePlaceholder: "e.g. SOL breakout",
  tokenAddressLabel: "TOKEN ADDRESS",
  alertTokenAddress: "Alert token address",
  solanaMintAddress: "Solana mint address",
  signal: "SIGNAL",
  oneHourChange: "1h change",
  volumeSpike: "Volume spike",
  price: "Price",
  aboveChoice: "Above",
  belowChoice: "Below",
  targetUsd: "TARGET USD",
  changePercent: "CHANGE %",
  volumeMultiplier: "VOLUME MULTIPLIER",
  alertThreshold: "Alert threshold",
  positiveValue: "Positive value",
  alertDeliveryDisclosure:
    "Channel: in-app · Cooldown: 60 minutes · Delivery is proven only after a recorded outcome.",
  saveAlertRule: "Save alert rule",
  saveDatabaseRule: "Save database rule",
  pauseAlert: "Pause {name}",
  activateAlert: "Activate {name}",
  alertHistory: "{count} triggers · last {last} · DB persisted",
  never: "never",
  deleteAlert: "Delete {name}",
  deleting: "Deleting…",
  loadingDeliveries: "Loading durable delivery outcomes…",
  deliveryLedgerBoundary:
    "Database delivery ledger · queued is not delivered · unavailable includes an explicit reason",
  deliveryEvent: "event {event}",
  noDeliveries:
    "No delivery attempt has been recorded. An enabled rule is not evidence of delivery.",
  unlockPrivateAlerts: "Unlock private alerts",
  privateAlertsBoundary:
    "Alert definitions and delivery history are owner-scoped private resources. Android wallet verification or biometric unlock is required.",
  unlockAlerts: "Unlock private alerts",
  priceCondition: "Price {condition} ${value}",
  changeCondition: "1h change {condition} {value}%",
  volumeCondition: "1h volume ≥ {value}× baseline",
  daysAgo: "{count}d ago",
  portfolioLocked: "Portfolio locked",
  portfolioLockedHint:
    "Re-authenticate with biometrics or your device credential before showing the verified wallet.",
  unlocking: "Unlocking…",
  unlockPortfolio: "Unlock portfolio",
  revokeSession: "Revoke session",
  ownershipVerified: "OWNERSHIP VERIFIED",
  connectSecurely: "Connect securely",
  walletSafety:
    "Terminal DEX never requests or stores seed phrases. Android uses Mobile Wallet Adapter to sign a non-transaction ownership challenge.",
  openingWallet: "Opening wallet…",
  connectVerify: "Connect & verify wallet",
  orWatchOnly: "OR WATCH ONLY",
  watchAddress: "Watch-only wallet address",
  walletPlaceholder: "Solana wallet address",
  loadWatchWallet: "Load watch-only wallet",
  load: "Load",
  watchOnlyHint:
    "Watch-only addresses are public data and do not prove ownership.",
  verifiedWallet: "VERIFIED WALLET",
  disconnectRevoke: "Disconnect & revoke",
  watchOnly: "WATCH ONLY",
  remove: "Remove",
  loadingHoldings: "Loading provider-backed holdings…",
  portfolioValue: "Portfolio value",
  tokens: "Tokens",
  weightedRisk: "Weighted risk",
  allocation: "Allocation",
  noPricedHoldings: "No priced holdings were returned.",
  holdings: "Holdings",
  pnlEvidence: "PnL evidence",
  loadingPnlEvidence: "Loading PnL evidence…",
  status: "Status",
  realizedPnl: "Realized PnL",
  unrealizedPnl: "Unrealized PnL",
  indexedSwaps: "Indexed swaps",
  connectPortfolioHint:
    "Connect a wallet or load a watch-only address to view real holdings.",
  portfolioProvenance:
    "Source: {source} · Quality: {quality}. Unavailable: {unavailable}.",
  goBack: "Go back",
  refreshToken: "Refresh token details",
  invalidLink: "Invalid link",
  invalidTokenLink:
    "This token link does not contain a valid 32-byte Solana address.",
  loadingToken: "Loading verified token detail…",
  noTokenRecord: "No validated token record was returned.",
  overview: "Overview",
  chart: "Chart",
  holdersTab: "Holders",
  trades: "Trades",
  risk: "Risk",
  intel: "Intel",
  pairs: "Pairs",
  selectTokenTab: "Select {tab} token view",
  degraded: "DEGRADED",
  liveDetail: "LIVE DETAIL",
  holderSource: "Holder source",
  largestHolders: "Largest observed holders",
  holderLimitation:
    "Holder rows may be sampled. Exactness is shown by backend evidence and must not be inferred from row count.",
  holderClusters: "Holder cluster evidence",
  graphSource: "Graph source",
  edgeSemantics: "Edge semantics",
  observedEdges: "Observed edges",
  observedNodes: "Observed nodes",
  clusterLimitation:
    "Cluster evidence uses {history} transaction history. Transfers or inferred membership indicate observations, not common ownership.",
  dataQuality: "Data quality",
  freshness: "Freshness",
  observedTransactions: "Observed transactions",
  tradeHistoryLimitation:
    "This is observed partial history, not a complete ledger or tax record.",
  behaviorEvidence: "Indexed transaction behavior",
  observedBehaviorScore: "OBSERVED BEHAVIOR SCORE",
  indexedWallets: "Indexed wallets",
  roundTripWalletShare: "Rapid round-trip wallet share",
  topTraderVolumeShare: "Top trader volume share",
  observedFlag: "OBSERVED FLAG",
  behaviorLimitation:
    "Heuristics are indicators, not proof. Unavailable analysis: {unavailable}.",
  earlyBuyers: "Observed early buyers",
  observedEarlyBuyers: "Detected rows",
  secondsAfterPair: "{seconds}s after pair",
  earlyBuyerLimitation:
    "Provider-derived buys within five minutes of the observed pair creation time. A detected row is not proof of malicious intent; an empty result is not proof that early buying was absent.",
  securityHistory: "Security history",
  observedSnapshots: "Observed snapshots",
  mintRenounced: "mint renounced",
  mintAuthorityPresent: "mint authority present",
  freezeRenounced: "freeze renounced",
  freezeAuthorityPresent: "freeze authority present",
  honeypotObserved: "honeypot flag observed",
  noProviderFlags: "no provider flags",
  securityHistoryLimitation:
    "Provider-backed persisted snapshots show observations over time, not continuous coverage or a guarantee of safety. Missing snapshots and unchanged flags are not evidence of absence.",
  safetyScore: "SAFETY SCORE",
  riskLimitation:
    "Risk scoring is decision support, not a guarantee. Missing inputs reduce confidence and execution remains locked.",
  reportedDepthLimitation:
    "Reported liquidity is not guaranteed executable depth.",
  snipers: "Snipers",
  dayChange: "24h change",
  dataEvidence: "Data evidence",
  quality: "Quality",
  priceAutomation: "Price automation",
  securityAutomation: "Security automation",
  verifiedReady: "verified ready",
  notVerified: "not verified",
  liveRefreshFailed: "Live refresh failed: {error}",
  tradingLocked:
    "Trading is locked. Execution requires ownership, a fresh quote, simulation, explicit confirmation, and server policy approval.",
  selectTimeframe: "Select {timeframe} chart timeframe",
  chartUnavailable: "Chart unavailable",
  loadingCandles: "Loading verified candles…",
  loadingIntelligence: "Loading token intelligence…",
  confidence: "Confidence",
  methodSources: "Method sources",
  narrativeUnavailable: "Narrative unavailable.",
  smartMoneySignals: "Smart-money signals",
  noEvidenceDescription: "No evidence description",
  noSmartMoneySignals: "No verified smart-money signals in this window.",
  intelligenceLimitation:
    "Narratives and wallet labels are probabilistic evidence, not instructions to trade.",
  loadingBackendData: "Loading verified backend data…",
  dataUnavailable: "Data unavailable",
  noValidatedResponse: "No validated response was returned.",
  invalidTradeLink:
    "Invalid token link. A valid 32-byte Solana address is required.",
  noQuoteRequest: "No token or quote request was made.",
  backInvalidTrade: "Go back from invalid trade link",
  nonExecutingReview: "NON-EXECUTING REVIEW",
  swapQuote: "Swap quote",
  tokenDetailUnavailable: "Token detail unavailable.",
  buy: "Buy",
  sell: "Sell",
  selectSide: "Select {side} quote side",
  amount: "Amount",
  swapAmount: "Swap amount",
  selectUnit: "Select {unit} amount unit",
  maximumSlippage: "Maximum slippage",
  selectSlippage: "Select {slippage} maximum slippage",
  refreshQuote: "Refresh quote",
  getRealQuote: "Get real quote",
  noTransactionBuilt: "No transaction was built or submitted.",
  jupiterRouteReview: "Jupiter route review",
  expired: "EXPIRED",
  youPay: "You pay",
  expectedOutput: "Expected output",
  minimumReceived: "Minimum received",
  priceImpact: "Price impact",
  route: "Route",
  contextSlot: "Context slot",
  quoteCheckAmounts: "Backend validated mint identities and exact raw amounts",
  quoteCheckExactIn: "ExactIn quote with {slippage}% slippage",
  quoteCheckIntermediate: "Intermediate tokens restricted by backend",
  quoteCheckUnsigned: "No unsigned transaction requested",
  quoteExpired:
    "This quote is older than the backend’s 15-second build window. Refresh before any later confirmation step.",
  executionLocked: "Execution locked",
  verifiedExecutionLocked:
    "Wallet ownership is verified, but build/sign/submit is deliberately unavailable until simulation, transaction decoding, explicit confirmation, and replay protection are implemented.",
  unverifiedExecutionLocked:
    "Connect and verify a wallet in Portfolio first. Quote review never authorizes a transaction.",
  buildUnavailable: "Build transaction unavailable.",
  backCopyTrade: "Back from CopyTrade",
  guardedStrategies: "GUARDED STRATEGIES",
  copyTradeSafety:
    "Mobile creates strategies paused. It never calls copy, confirmation, signature, close, or submit endpoints.",
  rank: "Rank",
  strategies: "Strategies",
  activity: "Activity",
  selectCopyTab: "Select {tab} CopyTrade view",
  loadingTraderOutcomes: "Loading observed trader outcomes…",
  sourceEvidence: "Source: {source} · {quality}",
  rankingLimitation:
    "Provider rankings or indexed realized PnL; never a promise of future returns.",
  selectRankingPeriod: "Select {period} ranking period",
  noRankings:
    "No provider or indexed wallet ranking evidence is currently available.",
  closedOutcomes: "{count} closed outcomes",
  winRate: "Win rate",
  drawdown: "Drawdown",
  best: "Best",
  reviewCopying: "Review copying {wallet}",
  reviewPausedStrategy: "Review paused strategy",
  verifyDurableRequired: "Verify wallet + durable storage required",
  reviewStrategy: "Review strategy",
  savesPaused: "{wallet} · saves paused",
  closeStrategyReview: "Close strategy review",
  copySizeSol: "COPY SIZE SOL",
  positionCapSol: "POSITION CAP SOL",
  dailyVolumeSol: "DAILY VOLUME SOL",
  dailyLossSol: "DAILY LOSS SOL",
  slippageBps: "SLIPPAGE BPS (≤500)",
  priceImpactLimit: "PRICE IMPACT % (≤5)",
  strategyDisclosure:
    "Fixed size · buys and sells observed · 20% stop · 50% take profit · $10K minimum liquidity · maximum 2 positions. Saving does not activate or authorize a transaction.",
  savePausedStrategyLabel: "Save paused CopyTrade strategy",
  saving: "Saving…",
  savePausedStrategy: "Save paused strategy",
  loadingStrategies: "Loading durable strategies…",
  strategyProvenance:
    "Wallet-owned database strategies · mobile can pause or remove, never activate",
  noStrategies:
    "No durable strategies. Choose a ranked wallet and save a paused review.",
  removeStrategyQuestion: "Remove strategy?",
  removeStrategyDescription:
    "This deletes its configuration. Existing execution evidence remains subject to backend retention.",
  activeOnServer: "ACTIVE ON SERVER",
  paused: "PAUSED",
  dbPersisted: "DB persisted",
  pauseStrategy: "Pause {strategy}",
  pausing: "Pausing…",
  pauseNow: "Pause now",
  copySize: "Copy size",
  positionCap: "Position cap",
  slippage: "Slippage",
  impact: "Impact",
  buys: "Buys",
  sells: "sells",
  maxPositions: "{count} max positions",
  deleteStrategy: "Delete {strategy}",
  delete: "Delete",
  loadingExecutionAudit: "Loading execution audit…",
  activityProvenance:
    "Read-only database audit · paper and live modes remain distinct",
  noCopyActivity:
    "No persisted CopyTrade positions or execution attempts are recorded.",
  modeUnavailable: "mode unavailable",
  entryAmount: "entry {amount} SOL",
  checking: "CHECKING",
  unlockCopyTrade: "Unlock CopyTrade",
  verifyWalletOwnership: "Verify wallet ownership",
  privateCopyResources:
    "Strategies, positions, and executions are private wallet-owned resources.",
  working: "Working…",
  unlock: "Unlock",
  verifyWallet: "Verify wallet",
  backAi: "Back from AI Intelligence",
  evidenceNotOracle: "EVIDENCE, NOT ORACLE",
  aiIntelligence: "AI Intelligence",
  executionOff: "EXECUTION OFF",
  aiSafety:
    "Every recommendation is advisory. Paper results are simulated and cannot authorize wallet signing, transaction construction, or submission.",
  advisories: "Advisories",
  paper: "Paper",
  governance: "Governance",
  selectAiTab: "Select {tab} AI view",
  loadingAdvisories: "Loading point-in-time recommendation evidence…",
  advisoryProvenance:
    "Public read-only recommendation history · current evidence must be point-in-time, cost-aware, and multi-provider",
  noAdvisories:
    "No persisted advisory recommendations are currently available.",
  openAdvisory: "Open {symbol} advisory evidence",
  score: "SCORE",
  providers: "Providers",
  costs: "Costs",
  pointTime: "Point-time",
  included: "included",
  missing: "missing",
  yes: "yes",
  no: "no",
  outcomesSummary: "{resolved}/{total} outcomes · {wins}W/{losses}L",
  unresolved: "unresolved",
  average: "avg",
  advisoryUnqualified: "Not qualified for advisory use: {reason}.",
  expiredReason: "expired",
  missingFeatures: "{count} missing features",
  incompleteEvidence: "incomplete evidence",
  loadingPaper: "Loading public simulation ledger…",
  paperUnavailable: "Paper report unavailable.",
  simulationLedger: "Simulation ledger",
  simulationMeta: "Read-only · kill switch on · {status}",
  equity: "Equity",
  totalPnl: "Total PnL",
  closed: "Closed",
  collecting: "Collecting",
  liveReadinessGate: "Live-readiness gate",
  locked: "LOCKED",
  operationalIntegrity: "Operational integrity",
  operationalEvidenceUnavailable: "Operational evidence unavailable.",
  cycleOperations: "Cycle operations",
  cycleOperationsDetail:
    "Cycle {cycle} · failed/abandoned 24h {failures} · reasons {reasons}",
  mutationRecovery: "Mutation recovery",
  mutationRecoveryDetail:
    "Qualified {qualified}/{audited} · manual review {review} · reasons {reasons}",
  jobLeaseFencing: "Job lease fencing",
  jobLeaseDetail: "Qualified {qualified}/{observed} · active leases {active}",
  cycleHistory: "Cycle history",
  cycleHistoryDetail:
    "Qualified terminal cycles {qualified}/{required} · running {running}",
  operationalIntegrityBoundary:
    "Read-only simulation evidence. Fail-closed recovery never replays an unknown partial operation; every health contract keeps execution disabled.",
  openSimulations: "Open simulations",
  noOpenSimulations: "No simulated positions open.",
  entryMark: "entry {entry} · mark {mark}",
  markUnavailable: "MARK N/A",
  recentClosedSimulations: "Recent closed simulations",
  noClosedSimulations: "No simulated trades closed.",
  adaptiveResearchPool: "Adaptive research pool",
  noCandidates: "No monitored candidates.",
  observationsProgress: "{count} observations · {minutes}/{required}m",
  loadingGovernance: "Loading wallet-owned governance evidence…",
  governanceUnavailable: "Governance unavailable.",
  phaseStatus: "Phase 31 · {status}",
  governanceProgress: "{trades}/500 closed trades · {days}/60 operating days",
  noExecution: "NO EXECUTION",
  evidenceRecords: "{status} · {count} records",
  unlockGovernance: "Unlock governance",
  governanceOwnerScope:
    "Detailed governance evidence is owner-scoped. Public recommendations and paper results remain available without mutation access.",
  backMarketIntel: "Back from Market Intelligence",
  readOnlyMarketEvidence: "READ-ONLY MARKET EVIDENCE",
  marketIntelligence: "Market Intelligence",
  noActions: "NO ACTIONS",
  marketIntelSafety:
    "Signature-backed observations and provider market snapshots are evidence, not trade instructions. This screen cannot sign, submit, claim, or move funds.",
  signals: "Signals",
  heatmap: "Heatmap",
  claims: "Claims",
  selectMarketIntelTab: "Select {tab} market intelligence view",
  selectSignalWindow: "Select {window} signal window",
  selectSignalType: "Filter signals by {type}",
  providerUnavailable: "provider unavailable",
  ingestion: "ingestion {status}",
  untracked: "untracked",
  loadingSignals: "Loading signature-backed market events…",
  noSignalEvents: "No signature-backed events in this window.",
  loadOlderSignals: "Load older signal evidence",
  loadOlderEvidence: "Load older evidence",
  openSignalToken: "Open {token} signal token",
  sourceUnavailable: "source unavailable",
  signatureUnavailable: "signature unavailable",
  loadingHeatmap: "Loading trustworthy market heatmap…",
  heatmapInclusion: "{source} · {included} included · {excluded} excluded",
  warnings: "Warnings",
  lowLiquidity: "Low liquidity",
  incomplete: "Incomplete",
  openHeatmapToken: "Open {symbol}, {change}",
  noHeatmapRecords: "No trustworthy heatmap records are available.",
  detected: "Detected",
  firstClaims: "First claims",
  unpaidFake: "Unpaid / fake",
  scanned: "Scanned",
  scanningClaims: "Scanning PumpFees transactions…",
  allClaims: "All claims",
  unpaidClaims: "Unpaid claims",
  selectClaimFilter: "Filter claim evidence by {filter}",
  noClaimEvents: "No claim events matched this filter.",
  claimBoundary:
    "Observation only · no claim instruction, wallet action, message delivery, or external URL is invoked.",
  githubSocialFee: "GitHub social fee",
  socialFeeClaim: "Social fee claim",
  slot: "slot {slot}",
  amountUnparsed: "amount unparsed",
  firstObservedClaim: "FIRST OBSERVED CLAIM",
  staleDegraded: "STALE / DEGRADED",
  current: "CURRENT",
  backWalletIntel: "Back from Wallet Intelligence",
  publicAddressResearch: "PUBLIC ADDRESS RESEARCH",
  walletIntelligence: "Wallet Intelligence",
  walletIntelSafety:
    "Public wallet holdings and indexed realized PnL do not prove ownership or predict future returns. No follow, copy, sign, or trade action is available here.",
  smartMoney: "Smart Money",
  walletTracker: "Wallet Tracker",
  selectWalletIntelTab: "Select {tab} wallet intelligence view",
  loadingWalletRankings: "Loading provider or indexed wallet rankings…",
  rankingEvidence: "{source} · {quality} · {freshness} · ranking is historical",
  stale: "stale",
  qualified: "Qualified",
  historicalPnl: "Historical PnL",
  averageWinRate: "Avg win rate",
  noSmartWallets:
    "No Smart Money or Whale wallets meet the current ranking evidence.",
  inspectWallet: "Inspect {badge} wallet {address}",
  indexedTradesReliability:
    "{trades} indexed trades · reliability {reliability}",
  maxDrawdown: "Max drawdown",
  bestObserved: "Best observed",
  loadingTrackedWallets: "Loading device-only tracked wallets…",
  trackedWalletBoundary:
    "Device-only labels and public addresses · maximum 50 · exact 32-byte Solana validation",
  addPublicWallet: "Add public wallet",
  trackedWalletAddress: "Tracked wallet address",
  trackedWalletLabel: "Tracked wallet label",
  solanaPublicAddress: "Solana public address",
  optionalLabel: "Label (optional)",
  saveTrackedWallet: "Save tracked wallet",
  saveWatchOnlyWallet: "Save watch-only wallet",
  exactSolanaKey: "Address must be an exact 32-byte base58 Solana key.",
  couldNotSaveWallet: "Could not save wallet.",
  noTrackedWallets: "No public wallets are stored on this device.",
  inspectTrackedWallet: "Inspect tracked wallet {label}",
  removeTrackedWallet: "Remove tracked wallet {label}",
  loadingWalletEvidence: "Loading public holdings and indexed PnL…",
  walletEvidence: "Wallet evidence",
  tokenAccounts: "Token accounts",
  walletEvidenceLimitation:
    "Holdings: backend Solana RPC aggregation with available DEX marks; only the enriched subset is listed. PnL: {method} · unrealized PnL unavailable.",
  unpriced: "unpriced",
  backResearch: "Back from Research Workspace",
  deviceOnlyResearch: "DEVICE-ONLY RESEARCH",
  researchWorkspace: "Research Workspace",
  researchSafety:
    "Lists, notes, thresholds, and chart slots stay on this device. Prices and candles come from validated backend contracts. Thresholds are visual checks only—not durable alerts or trade triggers.",
  snipeList: "Snipe List",
  multicharts: "Multicharts",
  selectResearchTab: "Select {tab} research view",
  loadingResearch: "Loading device research workspace…",
  storageUnavailable:
    "Device storage is unavailable; this change may not persist.",
  deviceCandidates: "{count}/20 device-only candidates",
  snipeAddress: "Snipe token address",
  exactTokenMint: "Exact Solana token mint",
  addSnipe: "Add token to Snipe List",
  addCandidate: "Add research candidate",
  exact32Bytes: "Address must decode to exactly 32 bytes.",
  noCandidatesResearch:
    "No candidates yet. Add an exact token mint to begin real price research.",
  researchBoundary:
    "For durable server-side price rules and delivery evidence, use Monitor alerts with a verified wallet. This local list never claims background monitoring.",
  openTokenResearch: "Open {symbol} token research",
  candidate: "candidate",
  removeSnipe: "Remove Snipe List candidate",
  loadingTokenEvidence: "Loading backend token evidence…",
  tokenUnavailable: "Token unavailable",
  visualThresholdMet: "VISUAL THRESHOLD MET WHILE OPEN · {direction}",
  above: "ABOVE",
  below: "BELOW",
  visualAboveUsd: "VISUAL ABOVE USD",
  visualBelowUsd: "VISUAL BELOW USD",
  visualAboveLabel: "Visual price above threshold",
  visualBelowLabel: "Visual price below threshold",
  none: "None",
  candidateNotes: "Candidate research notes",
  researchNotesPlaceholder: "Research notes (device only)",
  realChartsShared: "{count}/4 real token charts · shared timeframe",
  selectChartTimeframe: "Select {timeframe} shared chart timeframe",
  multichartAddress: "Multichart token address",
  addExactMint: "Add exact token mint",
  addTokenChart: "Add token chart",
  noCharts:
    "No charts configured. Add up to four exact token mints; no default or synthetic markets are inserted.",
  openChartToken: "Open {symbol} token detail",
  chartCandidate: "chart",
  refreshChart: "Refresh token chart",
  removeChart: "Remove token chart",
  loadingTokenIdentity: "Loading token identity…",
  loadingValidatedCandles: "Loading validated candles…",
  backOperations: "Back from Operations",
  readOnlyOperationalEvidence: "READ-ONLY OPERATIONAL EVIDENCE",
  analyticsFeeds: "Analytics & Feeds",
  getOnly: "GET ONLY",
  operationsSafety:
    "Market analytics summarize observed provider records. Feed Data observes runtime and persistence evidence; it never activates probes, changes providers, replays events, or exposes credentials.",
  analytics: "Analytics",
  feedData: "Feed Data",
  selectOperationsTab: "Select {tab} operations view",
  loadingAnalytics: "Loading live Solana analytics…",
  operationsEvidence:
    "{source} · {quality} · {included} exact-mint records · {excluded} excluded",
  qualityUnavailable: "quality unavailable",
  tracked: "Tracked",
  momentumLeaders: "Momentum leaders",
  momentumDetail: "Observed 1-hour change; not a prediction",
  noMomentum: "No exact-mint momentum records are available.",
  freshPairs: "Fresh pairs",
  canonicalDedup: "Deduplicated by canonical mint",
  noFreshPairs: "No exact-mint fresh pairs are available.",
  historicalTraderActivity: "Historical trader activity",
  thirtyDayObservation: "{source} · 30-day observation",
  indexedHistoricalWin:
    "{badge} · {trades} indexed trades · {winRate}% historical win rate",
  analyticsBoundary:
    "Aggregates use only canonical token identities returned by the backend. Missing transaction counts, cost basis, and predictive claims are not inferred.",
  loadingFeedEvidence: "Loading observational feed evidence…",
  feedEvidence: "{scope} · generated {age} · {receiving} receiving",
  healthy: "Healthy",
  unhealthy: "Unhealthy",
  receiving: "Receiving",
  runtimeQuality: "Runtime quality",
  recoveryDrilldown: "Recovery drill-down",
  runtimeCountersBoundary:
    "Cumulative backend counters · deltas appear after the next refresh",
  decodePipeline: "Observed decode pipeline",
  decodePipelineState: "Quality {quality} · cooldown {cooldown}",
  feedCounter_received: "Received",
  feedCounter_decoded: "Decoded",
  feedCounter_persisted: "Persisted",
  feedCounter_dropped: "Dropped",
  feedCounter_ignored: "Ignored",
  deltaSinceRefresh: "Delta since the previous successful refresh",
  awaitingCounterBaseline: "Awaiting the next refresh for counter deltas",
  runtimeCountersUnavailable: "Runtime decode counters are unavailable.",
  eventPersistencePipeline: "Event persistence pipeline",
  eventBusCounters:
    "Published {published} · persisted {persisted} · duplicate drops {duplicate} · invalid-time drops {invalid}",
  persistencePressure:
    "Persist failures {failed} · pressure drops {dropped} · pending {pending}",
  noRuntimeEvent: "No runtime event timestamp is available.",
  degradedEvidence: "degraded evidence",
  noReportedDegradation: "no reported degradation",
  persistenceEvidence: "Persistence evidence: {status}",
  observabilityEvidence: "Observability evidence: {status}",
  replayEvidence: "Replay evidence: {status}",
  realtimeTimestamp: "Realtime timestamp: {timestamp}",
  validUnavailable: "valid, unavailable",
  invalidUnavailable: "invalid / unavailable",
  providerInventory: "Provider inventory",
  configurationNotDelivery: "Configuration is not proof of live delivery",
  noFeedInventory: "No feed inventory evidence is available.",
  recentIngestionJobs: "Recent ingestion jobs",
  durableNoControls: "Durable job outcomes; no controls",
  jobOutcome: "{processed} ok · {failed} failed",
  noIngestionJobs: "No durable ingestion jobs were returned.",
  feedBoundary:
    "Read-only summary. Endpoint URLs, sample records, provider keys, active probes, replay controls, and scheduler mutations are intentionally absent.",
  persistedRecordsLabel: "{label}, {health}, {count} persisted records",
  connectionMeta: "{method} · {delivery} · {configuration}",
  subscriptionEvidence:
    "Connected {connected} · subscriptions {count} · receiving {receiving}",
  lastRuntimeSuccess: "Last runtime success: {age}",
  lastRuntimeError: "Last runtime error: {error}",
  rateLimitEvidence:
    "Requests {requests} · limited {limited} · queued {queued} · cooldown {cooldown}",
  notApplicable: "n/a",
  configured: "configured",
  notConfigured: "not configured",
  pairsCount: "{count} pairs",
  transactionsCount: "{count} txns",
  candlesCount: "{count} candles",
  freshnessUnavailable: "freshness unavailable",
  noPersistedObservation: "no persisted observation",
  timeUnavailable: "time unavailable",
  secondsAgo: "{count}s ago",
  minutesAgo: "{count}m ago",
  hoursAgo: "{count}h ago",
  openAnalytics: "Open {symbol} analytics",
  liquidityVolume: "LIQ {liquidity} · VOL {volume} · {dex}",
  check: "CHECK",
} as const;
type TranslationKey = keyof typeof en;
const vi: { [K in TranslationKey]: string } = {
  discover: "Khám phá",
  trenches: "Token mới",
  monitor: "Theo dõi",
  portfolio: "Danh mục",
  more: "Thêm",
  moreTools: "Công cụ khác",
  settings: "Cài đặt",
  privacySecurity: "Quyền riêng tư & bảo mật",
  privacyAccessibilityLanguages: "RIÊNG TƯ · TRỢ NĂNG · VI/EN",
  track: "Theo dõi trực tiếp",
  readOnlyTracking: "THEO DÕI CHỈ ĐỌC",
  refreshTrack: "Làm mới bằng chứng theo dõi",
  trackBoundary:
    "Chỉ có sự kiện được nhà cung cấp và chỉ mục quan sát. Track không theo dõi ví, đăng ký kênh xã hội, gửi cảnh báo hay thực thi giao dịch từ thiết bị này.",
  selectTrackFilter: "Chọn bộ lọc Track {filter}",
  trackFilter_all: "Tất cả",
  trackFilter_wallet: "Ví",
  trackFilter_kol: "KOL",
  trackFilter_social: "X / TG",
  loadingTrack: "Đang tải bằng chứng theo dõi…",
  trackUnavailable: "Bằng chứng theo dõi không khả dụng.",
  sourceStatus: "TRẠNG THÁI NGUỒN",
  launchPools: "Pool ra mắt",
  whaleTransactions: "Giao dịch cá voi",
  observedEventHistory: "LỊCH SỬ SỰ KIỆN QUAN SÁT",
  socialTrackUnavailable:
    "Sự kiện nguồn X/TG chưa được cung cấp qua hợp đồng an toàn cho di động. Quan sát chỉ từ mạng xã hội vẫn không khả dụng và không được suy diễn từ hoạt động thị trường.",
  noTrackEvents: "Không có sự kiện quan sát phù hợp.",
  trackCursorBoundary:
    "Backend trả về một cửa sổ quan sát giới hạn đã khử trùng lặp mà không có con trỏ. Lịch sử cũ hơn và theo dõi liên tục không khả dụng.",
  deliveryEvidence: "BẰNG CHỨNG PHÂN PHỐI BỀN VỮNG",
  verifyForDeliveryEvidence:
    "Xác minh quyền sở hữu ví để đọc sổ cái phân phối thuộc chủ sở hữu.",
  unlockForDeliveryEvidence:
    "Mở khóa phiên ví đã xác minh để đọc bằng chứng phân phối.",
  deliveryUnavailable: "Bằng chứng phân phối không khả dụng.",
  noDeliveryEvidence: "Không có bản ghi phân phối bền vững cho chủ sở hữu này.",
  openTrackEvent: "Mở bằng chứng theo dõi {type} của {symbol}",
  dedupeId: "khử trùng lặp {id}",
  retryTrack: "Thử lại bằng chứng theo dõi",
  copyTrade: "CopyTrade",
  topTraders: "Nhà giao dịch hàng đầu",
  claimMonitor: "Theo dõi nhận phí",
  openToolStatus: "{tool} {status}",
  realData: "DỮ LIỆU THẬT",
  searchTokens: "Tìm token trực tiếp hoặc địa chỉ mint",
  clearSearch: "Xóa tìm kiếm token",
  trending: "Xu hướng",
  gainers: "Tăng giá",
  losers: "Giảm giá",
  volume: "Khối lượng",
  newPairs: "Cặp mới",
  hotSearches: "Tìm kiếm nóng",
  surge: "Bứt phá",
  pumpLive: "Pump trực tiếp",
  watchlist: "Theo dõi",
  filter: "Bộ lọc",
  openFilters: "Mở bộ lọc thị trường",
  searching: "Đang tìm",
  marketFeed: "Nguồn thị trường",
  searchingSources: "Đang tìm nguồn thị trường thật…",
  loadingMarkets: "Đang tải thị trường trực tiếp…",
  loadingMoreMarkets: "Đang tải thêm bằng chứng thị trường…",
  marketUnavailable: "Không có dữ liệu thị trường",
  retry: "Thử lại",
  watchlistEmpty: "Danh sách theo dõi đang trống",
  noMatchingTokens: "Không có token phù hợp",
  watchlistHint: "Đánh dấu token từ danh sách Khám phá để lưu tại đây.",
  filtersHint: "Điều chỉnh bộ lọc, tìm kiếm hoặc chọn khung thị trường khác.",
  marketFilters: "Bộ lọc thị trường",
  closeFilters: "Đóng bộ lọc thị trường",
  all: "Tất cả",
  minLiquidity: "Thanh khoản tối thiểu (USD)",
  minMarketCap: "Vốn hóa tối thiểu (USD)",
  reset: "Đặt lại",
  applyFilters: "Áp dụng bộ lọc",
  selectMode: "Chọn danh sách thị trường {mode}",
  selectPeriod: "Chọn khung thị trường {period}",
  selectDex: "Chọn DEX {dex}",
  nextBc: "Sắp bonding",
  offlineBanner:
    "Ngoại tuyến · chỉ hiển thị bằng chứng đã tải. Yêu cầu và làm mới tự động đang tạm dừng.",
  recoveredBanner: "Đã kết nối lại · đang làm mới bằng chứng đang hoạt động.",
  liveLaunches: "TOKEN RA MẮT TRỰC TIẾP",
  new: "Mới",
  almostBonded: "Gần hoàn tất",
  migrated: "Đã chuyển",
  source: "Nguồn",
  loading: "đang tải",
  launchFeed: "nguồn token mới từ nhà cung cấp",
  loadingLaunches: "Đang tải nguồn token mới thật…",
  noLaunches: "Không có token {lane} đã xác minh.",
  openTrenchFilters: "Mở bộ lọc token mới",
  trenchMatches: "{shown} / {total} token mới",
  noTrenchMatches: "Không có token mới khớp bộ lọc đang bật.",
  trenchKeyword: "Ký hiệu, tên hoặc địa chỉ token",
  selectLaunchpad: "Chọn launchpad {launchpad}",
  minVolume24h: "KL 24 giờ tối thiểu",
  maxAgeMinutes: "Tuổi tối đa (phút)",
  minBondingProgress: "Bonding tối thiểu (%)",
  openLaunch: "Mở chi tiết token mới {symbol}",
  reviewQuoteLabel: "Xem báo giá {symbol}",
  bondingProgress: "Tiến độ bonding",
  marketCap: "Vốn hóa",
  liquidity: "Thanh khoản",
  hourVolume: "KL 1 giờ",
  buysSells: "Mua/Bán 5 phút",
  reviewQuote: "Xem báo giá",
  unknown: "không rõ",
  unavailable: "không có",
  routesNote:
    "Chỉ mở chức năng sau khi hợp đồng dữ liệu thật và kiểm tra bảo mật đã hoàn tất.",
  openSettings: "Mở Cài đặt",
  intelligenceAutomation: "TRÍ TUỆ & TỰ ĐỘNG HÓA",
  automationWarning:
    "CopyTrade chỉ lưu chiến lược tạm dừng. Khuyến nghị AI chỉ mang tính tham khảo và mô phỏng.",
  available: "khả dụng",
  queued: "đang chờ",
  open: "MỞ",
  deviceControls: "ĐIỀU KHIỂN THIẾT BỊ",
  backSettings: "Quay lại từ Cài đặt",
  language: "Ngôn ngữ / Language",
  languageDescription:
    "Tất cả tab chính cập nhật ngay. Ký hiệu thị trường và bằng chứng nhà cung cấp giữ nguyên để bảo toàn ý nghĩa chính xác.",
  accessibility: "Trợ năng",
  accessibilityDescription:
    "Terminal DEX tôn trọng cỡ chữ và trình đọc màn hình của hệ điều hành. Điều khiển có vai trò, trạng thái, nhãn và trạng thái chọn hoặc vô hiệu hóa.",
  reduceMotion: "Giảm chuyển động",
  reduceMotionDetail:
    "Tắt chuyển động tùy chọn; làm mới thị trường trực tiếp vẫn hoạt động.",
  telemetryDescription:
    "Chẩn đoán bị tắt mặc định. Nếu bật sau này, dữ liệu giới hạn được xóa thông tin xác thực, chữ ký và địa chỉ trước khi truyền.",
  diagnosticTelemetry: "Chẩn đoán từ xa",
  noTelemetry: "Bản dựng này không cấu hình kênh chẩn đoán.",
  transportSecurity:
    "API sản xuất bắt buộc HTTPS. iOS không cho tải tùy ý và Android chặn lưu lượng văn bản rõ.",
  deepLinkSecurity:
    "Địa chỉ token trong liên kết sâu phải giải mã đúng 32 byte; snapshot giới hạn 12 KB và phải khớp tuyến.",
  walletSecurity:
    "Siêu dữ liệu ví đã xác minh ở bộ nhớ bảo mật trên thiết bị và tự khóa lại khi ứng dụng chạy nền.",
  dataControls: "Điều khiển dữ liệu",
  dataControlsDescription:
    "Đặt lại chỉ ảnh hưởng bản cài này. Cảnh báo, chiến lược CopyTrade và dữ liệu máy chủ cần luồng xóa đã xác thực riêng.",
  clearQuestion: "Xóa dữ liệu riêng tư và cục bộ?",
  clearDescription:
    "Thao tác này ngắt ví, thu hồi phiên và xóa địa chỉ, danh sách theo dõi, bộ lọc, nghiên cứu và tùy chọn cục bộ. Dữ liệu máy chủ không bị xóa.",
  cancel: "Hủy",
  clearLocalData: "Xóa dữ liệu cục bộ",
  clearing: "Đang xóa…",
  disconnectClear: "Ngắt kết nối và xóa dữ liệu cục bộ",
  clearComplete: "Đã ngắt kết nối ví và xóa dữ liệu ứng dụng cục bộ.",
  clearFailed:
    "Không thể hoàn tất việc xóa toàn bộ dữ liệu cục bộ. Hãy kiểm tra trạng thái thiết bị và thử lại.",
  footerSecurity:
    "Terminal DEX Mobile 0.1.0 · không lưu ký · không lưu khóa bí mật",
  observationDesk: "BÀN QUAN SÁT",
  live: "Trực tiếp",
  rules: "Quy tắc",
  delivery: "Phân phối",
  connecting: "ĐANG KẾT NỐI",
  selectMonitorView: "Chọn chế độ theo dõi {view}",
  loadingActivity: "Đang tải hoạt động Solana quan sát được…",
  noActivity:
    "Hiện không có quan sát on-chain đã lập chỉ mục. Nguồn này không tạo dữ liệu giả.",
  signedObservations: "{count} quan sát có chữ ký · làm mới 30 giây",
  openMonitorToken: "Mở chi tiết {symbol}",
  loadingRules: "Đang tải quy tắc từ cơ sở dữ liệu…",
  alertRules: "Quy tắc cảnh báo",
  rulesSchedulerBoundary:
    "Được bộ lập lịch máy chủ đánh giá; di động không tuyên bố thực thi nền.",
  createAlertRule: "Tạo quy tắc cảnh báo",
  close: "Đóng",
  newRule: "Quy tắc mới",
  noAlertRules:
    "Chưa có quy tắc cảnh báo bền vững. Hãy tạo sau khi xác minh quyền sở hữu ví.",
  ruleName: "TÊN QUY TẮC",
  alertName: "Tên cảnh báo",
  alertNamePlaceholder: "ví dụ: SOL bứt phá",
  tokenAddressLabel: "ĐỊA CHỈ TOKEN",
  alertTokenAddress: "Địa chỉ token cảnh báo",
  solanaMintAddress: "Địa chỉ mint Solana",
  signal: "TÍN HIỆU",
  oneHourChange: "Thay đổi 1 giờ",
  volumeSpike: "Tăng vọt khối lượng",
  price: "Giá",
  aboveChoice: "Trên",
  belowChoice: "Dưới",
  targetUsd: "MỤC TIÊU USD",
  changePercent: "THAY ĐỔI %",
  volumeMultiplier: "HỆ SỐ KHỐI LƯỢNG",
  alertThreshold: "Ngưỡng cảnh báo",
  positiveValue: "Giá trị dương",
  alertDeliveryDisclosure:
    "Kênh: trong ứng dụng · Thời gian chờ: 60 phút · Chỉ chứng minh phân phối sau khi có kết quả được ghi nhận.",
  saveAlertRule: "Lưu quy tắc cảnh báo",
  saveDatabaseRule: "Lưu quy tắc cơ sở dữ liệu",
  pauseAlert: "Tạm dừng {name}",
  activateAlert: "Kích hoạt {name}",
  alertHistory: "{count} lần kích hoạt · gần nhất {last} · đã lưu DB",
  never: "chưa bao giờ",
  deleteAlert: "Xóa {name}",
  deleting: "Đang xóa…",
  loadingDeliveries: "Đang tải kết quả phân phối bền vững…",
  deliveryLedgerBoundary:
    "Sổ cái phân phối cơ sở dữ liệu · đang chờ không phải đã giao · không khả dụng có lý do rõ ràng",
  deliveryEvent: "sự kiện {event}",
  noDeliveries:
    "Chưa ghi nhận lần phân phối nào. Quy tắc bật không phải bằng chứng đã phân phối.",
  unlockPrivateAlerts: "Mở khóa cảnh báo riêng tư",
  privateAlertsBoundary:
    "Định nghĩa cảnh báo và lịch sử phân phối là tài nguyên riêng thuộc chủ sở hữu. Cần xác minh ví Android hoặc mở khóa sinh trắc học.",
  unlockAlerts: "Mở khóa cảnh báo riêng tư",
  priceCondition: "Giá {condition} ${value}",
  changeCondition: "Thay đổi 1 giờ {condition} {value}%",
  volumeCondition: "Khối lượng 1 giờ ≥ {value}× cơ sở",
  daysAgo: "{count} ngày trước",
  portfolioLocked: "Danh mục đã khóa",
  portfolioLockedHint:
    "Xác thực lại bằng sinh trắc học hoặc thông tin thiết bị trước khi hiển thị ví đã xác minh.",
  unlocking: "Đang mở khóa…",
  unlockPortfolio: "Mở khóa danh mục",
  revokeSession: "Thu hồi phiên",
  ownershipVerified: "ĐÃ XÁC MINH QUYỀN SỞ HỮU",
  connectSecurely: "Kết nối an toàn",
  walletSafety:
    "Terminal DEX không yêu cầu hoặc lưu cụm từ khôi phục. Android dùng Mobile Wallet Adapter để ký thử thách sở hữu không phải giao dịch.",
  openingWallet: "Đang mở ví…",
  connectVerify: "Kết nối và xác minh ví",
  orWatchOnly: "HOẶC CHỈ THEO DÕI",
  watchAddress: "Địa chỉ ví chỉ theo dõi",
  walletPlaceholder: "Địa chỉ ví Solana",
  loadWatchWallet: "Tải ví chỉ theo dõi",
  load: "Tải",
  watchOnlyHint:
    "Địa chỉ chỉ theo dõi là dữ liệu công khai và không chứng minh quyền sở hữu.",
  verifiedWallet: "VÍ ĐÃ XÁC MINH",
  disconnectRevoke: "Ngắt kết nối và thu hồi",
  watchOnly: "CHỈ THEO DÕI",
  remove: "Xóa",
  loadingHoldings: "Đang tải tài sản từ nhà cung cấp…",
  portfolioValue: "Giá trị danh mục",
  tokens: "Token",
  weightedRisk: "Rủi ro trọng số",
  allocation: "Phân bổ",
  noPricedHoldings: "Không có tài sản định giá được trả về.",
  holdings: "Tài sản",
  pnlEvidence: "Bằng chứng PnL",
  loadingPnlEvidence: "Đang tải bằng chứng PnL…",
  status: "Trạng thái",
  realizedPnl: "PnL đã thực hiện",
  unrealizedPnl: "PnL chưa thực hiện",
  indexedSwaps: "Swap đã lập chỉ mục",
  connectPortfolioHint:
    "Kết nối ví hoặc tải địa chỉ chỉ theo dõi để xem tài sản thật.",
  portfolioProvenance:
    "Nguồn: {source} · Chất lượng: {quality}. Không có: {unavailable}.",
  goBack: "Quay lại",
  refreshToken: "Làm mới chi tiết token",
  invalidLink: "Liên kết không hợp lệ",
  invalidTokenLink: "Liên kết token không chứa địa chỉ Solana 32 byte hợp lệ.",
  loadingToken: "Đang tải chi tiết token đã xác minh…",
  noTokenRecord: "Không nhận được bản ghi token đã xác thực.",
  overview: "Tổng quan",
  chart: "Biểu đồ",
  holdersTab: "Người nắm giữ",
  trades: "Giao dịch",
  risk: "Rủi ro",
  intel: "Phân tích",
  pairs: "Cặp",
  selectTokenTab: "Chọn chế độ token {tab}",
  degraded: "SUY GIẢM",
  liveDetail: "CHI TIẾT TRỰC TIẾP",
  holderSource: "Nguồn người nắm giữ",
  largestHolders: "Người nắm giữ quan sát lớn nhất",
  holderLimitation:
    "Các hàng có thể được lấy mẫu. Độ chính xác do bằng chứng máy chủ thể hiện, không được suy ra từ số hàng.",
  holderClusters: "Bằng chứng cụm người nắm giữ",
  graphSource: "Nguồn đồ thị",
  edgeSemantics: "Ý nghĩa cạnh",
  observedEdges: "Cạnh quan sát được",
  observedNodes: "Nút quan sát được",
  clusterLimitation:
    "Bằng chứng cụm dùng lịch sử giao dịch {history}. Chuyển khoản hoặc quan hệ thành viên suy luận là quan sát, không chứng minh cùng chủ sở hữu.",
  dataQuality: "Chất lượng dữ liệu",
  freshness: "Độ mới",
  observedTransactions: "Giao dịch quan sát được",
  tradeHistoryLimitation:
    "Đây là lịch sử quan sát một phần, không phải sổ cái hoàn chỉnh hay hồ sơ thuế.",
  behaviorEvidence: "Hành vi giao dịch đã lập chỉ mục",
  observedBehaviorScore: "ĐIỂM HÀNH VI QUAN SÁT",
  indexedWallets: "Ví đã lập chỉ mục",
  roundTripWalletShare: "Tỷ lệ ví khứ hồi nhanh",
  topTraderVolumeShare: "Tỷ trọng khối lượng nhà giao dịch lớn nhất",
  observedFlag: "CỜ QUAN SÁT",
  behaviorLimitation:
    "Heuristic là chỉ báo, không phải bằng chứng kết luận. Phân tích chưa có: {unavailable}.",
  earlyBuyers: "Người mua sớm được quan sát",
  observedEarlyBuyers: "Dòng phát hiện",
  secondsAfterPair: "{seconds} giây sau khi tạo cặp",
  earlyBuyerLimitation:
    "Các lệnh mua do nhà cung cấp ghi nhận trong vòng năm phút sau thời điểm tạo cặp được quan sát. Dòng được phát hiện không chứng minh ý đồ xấu; kết quả trống không chứng minh không có mua sớm.",
  securityHistory: "Lịch sử bảo mật",
  observedSnapshots: "Snapshot được quan sát",
  mintRenounced: "quyền mint đã từ bỏ",
  mintAuthorityPresent: "quyền mint còn tồn tại",
  freezeRenounced: "quyền đóng băng đã từ bỏ",
  freezeAuthorityPresent: "quyền đóng băng còn tồn tại",
  honeypotObserved: "đã quan sát cờ honeypot",
  noProviderFlags: "không có cờ từ nhà cung cấp",
  securityHistoryLimitation:
    "Snapshot bền vững từ nhà cung cấp thể hiện quan sát theo thời gian, không phải phạm vi liên tục hay bảo đảm an toàn. Snapshot bị thiếu và cờ không đổi không chứng minh rủi ro không tồn tại.",
  safetyScore: "ĐIỂM AN TOÀN",
  riskLimitation:
    "Điểm rủi ro chỉ hỗ trợ quyết định, không phải bảo đảm. Thiếu đầu vào làm giảm độ tin cậy và thực thi vẫn bị khóa.",
  reportedDepthLimitation:
    "Thanh khoản báo cáo không bảo đảm độ sâu có thể thực thi.",
  snipers: "Ví mua sớm",
  dayChange: "Thay đổi 24 giờ",
  dataEvidence: "Bằng chứng dữ liệu",
  quality: "Chất lượng",
  priceAutomation: "Tự động hóa giá",
  securityAutomation: "Tự động hóa bảo mật",
  verifiedReady: "đã xác minh sẵn sàng",
  notVerified: "chưa xác minh",
  liveRefreshFailed: "Làm mới trực tiếp thất bại: {error}",
  tradingLocked:
    "Giao dịch bị khóa. Thực thi cần quyền sở hữu, báo giá mới, mô phỏng, xác nhận rõ ràng và phê duyệt chính sách máy chủ.",
  selectTimeframe: "Chọn khung biểu đồ {timeframe}",
  chartUnavailable: "Biểu đồ không khả dụng",
  loadingCandles: "Đang tải nến đã xác minh…",
  loadingIntelligence: "Đang tải phân tích token…",
  confidence: "Độ tin cậy",
  methodSources: "Nguồn phương pháp",
  narrativeUnavailable: "Không có tường thuật.",
  smartMoneySignals: "Tín hiệu dòng tiền thông minh",
  noEvidenceDescription: "Không có mô tả bằng chứng",
  noSmartMoneySignals:
    "Không có tín hiệu dòng tiền thông minh đã xác minh trong cửa sổ này.",
  intelligenceLimitation:
    "Tường thuật và nhãn ví là bằng chứng xác suất, không phải hướng dẫn giao dịch.",
  loadingBackendData: "Đang tải dữ liệu máy chủ đã xác minh…",
  dataUnavailable: "Dữ liệu không khả dụng",
  noValidatedResponse: "Không nhận được phản hồi đã xác thực.",
  invalidTradeLink:
    "Liên kết token không hợp lệ. Cần địa chỉ Solana 32 byte hợp lệ.",
  noQuoteRequest: "Không có yêu cầu token hoặc báo giá nào được gửi.",
  backInvalidTrade: "Quay lại từ liên kết giao dịch không hợp lệ",
  nonExecutingReview: "XEM XÉT KHÔNG THỰC THI",
  swapQuote: "Báo giá swap",
  tokenDetailUnavailable: "Chi tiết token không khả dụng.",
  buy: "Mua",
  sell: "Bán",
  selectSide: "Chọn phía báo giá {side}",
  amount: "Số lượng",
  swapAmount: "Số lượng swap",
  selectUnit: "Chọn đơn vị số lượng {unit}",
  maximumSlippage: "Trượt giá tối đa",
  selectSlippage: "Chọn trượt giá tối đa {slippage}",
  refreshQuote: "Làm mới báo giá",
  getRealQuote: "Lấy báo giá thật",
  noTransactionBuilt: "Không có giao dịch nào được tạo hoặc gửi.",
  jupiterRouteReview: "Xem xét tuyến Jupiter",
  expired: "HẾT HẠN",
  youPay: "Bạn trả",
  expectedOutput: "Đầu ra dự kiến",
  minimumReceived: "Nhận tối thiểu",
  priceImpact: "Tác động giá",
  route: "Tuyến",
  contextSlot: "Slot ngữ cảnh",
  quoteCheckAmounts:
    "Máy chủ đã xác thực danh tính mint và số lượng thô chính xác",
  quoteCheckExactIn: "Báo giá ExactIn với trượt giá {slippage}%",
  quoteCheckIntermediate: "Token trung gian bị giới hạn bởi máy chủ",
  quoteCheckUnsigned: "Không yêu cầu giao dịch chưa ký",
  quoteExpired:
    "Báo giá này cũ hơn cửa sổ tạo 15 giây của máy chủ. Hãy làm mới trước bước xác nhận sau này.",
  executionLocked: "Thực thi bị khóa",
  verifiedExecutionLocked:
    "Quyền sở hữu ví đã xác minh, nhưng tạo/ký/gửi bị vô hiệu hóa có chủ đích cho đến khi có mô phỏng, giải mã giao dịch, xác nhận rõ ràng và chống phát lại.",
  unverifiedExecutionLocked:
    "Trước tiên hãy kết nối và xác minh ví trong Danh mục. Xem báo giá không bao giờ cho phép giao dịch.",
  buildUnavailable: "Không thể tạo giao dịch.",
  backCopyTrade: "Quay lại từ CopyTrade",
  guardedStrategies: "CHIẾN LƯỢC ĐƯỢC BẢO VỆ",
  copyTradeSafety:
    "Di động tạo chiến lược ở trạng thái tạm dừng. Ứng dụng không gọi điểm cuối sao chép, xác nhận, ký, đóng hoặc gửi.",
  rank: "Xếp hạng",
  strategies: "Chiến lược",
  activity: "Hoạt động",
  selectCopyTab: "Chọn chế độ CopyTrade {tab}",
  loadingTraderOutcomes: "Đang tải kết quả nhà giao dịch quan sát được…",
  sourceEvidence: "Nguồn: {source} · {quality}",
  rankingLimitation:
    "Xếp hạng nhà cung cấp hoặc PnL đã thực hiện được lập chỉ mục; không bao giờ là cam kết lợi nhuận tương lai.",
  selectRankingPeriod: "Chọn kỳ xếp hạng {period}",
  noRankings:
    "Hiện không có bằng chứng xếp hạng ví từ nhà cung cấp hoặc chỉ mục.",
  closedOutcomes: "{count} kết quả đã đóng",
  winRate: "Tỷ lệ thắng",
  drawdown: "Sụt giảm",
  best: "Tốt nhất",
  reviewCopying: "Xem xét sao chép {wallet}",
  reviewPausedStrategy: "Xem chiến lược tạm dừng",
  verifyDurableRequired: "Cần xác minh ví và lưu trữ bền vững",
  reviewStrategy: "Xem xét chiến lược",
  savesPaused: "{wallet} · lưu ở trạng thái tạm dừng",
  closeStrategyReview: "Đóng xem xét chiến lược",
  copySizeSol: "KÍCH THƯỚC SAO CHÉP SOL",
  positionCapSol: "GIỚI HẠN VỊ THẾ SOL",
  dailyVolumeSol: "KHỐI LƯỢNG NGÀY SOL",
  dailyLossSol: "THUA LỖ NGÀY SOL",
  slippageBps: "TRƯỢT GIÁ BPS (≤500)",
  priceImpactLimit: "TÁC ĐỘNG GIÁ % (≤5)",
  strategyDisclosure:
    "Kích thước cố định · quan sát mua và bán · dừng lỗ 20% · chốt lời 50% · thanh khoản tối thiểu $10K · tối đa 2 vị thế. Lưu không kích hoạt hoặc cho phép giao dịch.",
  savePausedStrategyLabel: "Lưu chiến lược CopyTrade tạm dừng",
  saving: "Đang lưu…",
  savePausedStrategy: "Lưu chiến lược tạm dừng",
  loadingStrategies: "Đang tải chiến lược bền vững…",
  strategyProvenance:
    "Chiến lược cơ sở dữ liệu thuộc ví · di động có thể tạm dừng hoặc xóa, không bao giờ kích hoạt",
  noStrategies:
    "Không có chiến lược bền vững. Chọn ví xếp hạng và lưu bản xem xét tạm dừng.",
  removeStrategyQuestion: "Xóa chiến lược?",
  removeStrategyDescription:
    "Thao tác xóa cấu hình. Bằng chứng thực thi hiện có vẫn theo chính sách lưu giữ máy chủ.",
  activeOnServer: "ĐANG HOẠT ĐỘNG TRÊN MÁY CHỦ",
  paused: "TẠM DỪNG",
  dbPersisted: "Đã lưu DB",
  pauseStrategy: "Tạm dừng {strategy}",
  pausing: "Đang tạm dừng…",
  pauseNow: "Tạm dừng ngay",
  copySize: "Kích thước sao chép",
  positionCap: "Giới hạn vị thế",
  slippage: "Trượt giá",
  impact: "Tác động",
  buys: "Mua",
  sells: "bán",
  maxPositions: "tối đa {count} vị thế",
  deleteStrategy: "Xóa {strategy}",
  delete: "Xóa",
  loadingExecutionAudit: "Đang tải kiểm tra thực thi…",
  activityProvenance:
    "Kiểm tra cơ sở dữ liệu chỉ đọc · chế độ mô phỏng và trực tiếp vẫn tách biệt",
  noCopyActivity: "Không ghi nhận vị thế CopyTrade hoặc lần thực thi nào.",
  modeUnavailable: "không có chế độ",
  entryAmount: "vào lệnh {amount} SOL",
  checking: "ĐANG KIỂM TRA",
  unlockCopyTrade: "Mở khóa CopyTrade",
  verifyWalletOwnership: "Xác minh quyền sở hữu ví",
  privateCopyResources:
    "Chiến lược, vị thế và thực thi là tài nguyên riêng thuộc ví.",
  working: "Đang xử lý…",
  unlock: "Mở khóa",
  verifyWallet: "Xác minh ví",
  backAi: "Quay lại từ AI Intelligence",
  evidenceNotOracle: "BẰNG CHỨNG, KHÔNG PHẢI TIÊN TRI",
  aiIntelligence: "Trí tuệ AI",
  executionOff: "TẮT THỰC THI",
  aiSafety:
    "Mọi khuyến nghị chỉ mang tính tham khảo. Kết quả mô phỏng không thể cho phép ký ví, tạo hoặc gửi giao dịch.",
  advisories: "Tham khảo",
  paper: "Mô phỏng",
  governance: "Quản trị",
  selectAiTab: "Chọn chế độ AI {tab}",
  loadingAdvisories: "Đang tải bằng chứng khuyến nghị tại thời điểm…",
  advisoryProvenance:
    "Lịch sử khuyến nghị công khai chỉ đọc · bằng chứng hiện tại phải theo thời điểm, tính chi phí và đa nhà cung cấp",
  noAdvisories: "Hiện không có khuyến nghị tham khảo đã lưu.",
  openAdvisory: "Mở bằng chứng tham khảo {symbol}",
  score: "ĐIỂM",
  providers: "Nhà cung cấp",
  costs: "Chi phí",
  pointTime: "Theo thời điểm",
  included: "đã tính",
  missing: "thiếu",
  yes: "có",
  no: "không",
  outcomesSummary: "{resolved}/{total} kết quả · {wins} thắng/{losses} thua",
  unresolved: "chưa giải quyết",
  average: "trung bình",
  advisoryUnqualified: "Không đủ điều kiện tham khảo: {reason}.",
  expiredReason: "đã hết hạn",
  missingFeatures: "thiếu {count} tính năng",
  incompleteEvidence: "bằng chứng chưa đầy đủ",
  loadingPaper: "Đang tải sổ cái mô phỏng công khai…",
  paperUnavailable: "Báo cáo mô phỏng không khả dụng.",
  simulationLedger: "Sổ cái mô phỏng",
  simulationMeta: "Chỉ đọc · công tắc dừng bật · {status}",
  equity: "Vốn",
  totalPnl: "Tổng PnL",
  closed: "Đã đóng",
  collecting: "Đang thu thập",
  liveReadinessGate: "Cổng sẵn sàng trực tiếp",
  locked: "ĐÃ KHÓA",
  operationalIntegrity: "Tính toàn vẹn vận hành",
  operationalEvidenceUnavailable: "Bằng chứng vận hành không khả dụng.",
  cycleOperations: "Vận hành chu kỳ",
  cycleOperationsDetail:
    "Chu kỳ {cycle} · lỗi/bị bỏ 24 giờ {failures} · lý do {reasons}",
  mutationRecovery: "Khôi phục thay đổi",
  mutationRecoveryDetail:
    "Đạt chuẩn {qualified}/{audited} · xem xét thủ công {review} · lý do {reasons}",
  jobLeaseFencing: "Hàng rào lease tác vụ",
  jobLeaseDetail:
    "Đạt chuẩn {qualified}/{observed} · lease đang hoạt động {active}",
  cycleHistory: "Lịch sử chu kỳ",
  cycleHistoryDetail:
    "Chu kỳ kết thúc đạt chuẩn {qualified}/{required} · đang chạy {running}",
  operationalIntegrityBoundary:
    "Bằng chứng mô phỏng chỉ đọc. Khôi phục đóng an toàn không bao giờ phát lại thao tác một phần chưa rõ; mọi hợp đồng sức khỏe đều giữ thực thi ở trạng thái tắt.",
  openSimulations: "Mô phỏng đang mở",
  noOpenSimulations: "Không có vị thế mô phỏng đang mở.",
  entryMark: "vào {entry} · định giá {mark}",
  markUnavailable: "KHÔNG CÓ GIÁ",
  recentClosedSimulations: "Mô phỏng đã đóng gần đây",
  noClosedSimulations: "Không có giao dịch mô phỏng đã đóng.",
  adaptiveResearchPool: "Nhóm nghiên cứu thích ứng",
  noCandidates: "Không có ứng viên theo dõi.",
  observationsProgress: "{count} quan sát · {minutes}/{required} phút",
  loadingGovernance: "Đang tải bằng chứng quản trị thuộc ví…",
  governanceUnavailable: "Quản trị không khả dụng.",
  phaseStatus: "Giai đoạn 31 · {status}",
  governanceProgress:
    "{trades}/500 giao dịch đã đóng · {days}/60 ngày vận hành",
  noExecution: "KHÔNG THỰC THI",
  evidenceRecords: "{status} · {count} bản ghi",
  unlockGovernance: "Mở khóa quản trị",
  governanceOwnerScope:
    "Bằng chứng quản trị chi tiết thuộc phạm vi chủ sở hữu. Khuyến nghị công khai và kết quả mô phỏng vẫn khả dụng mà không có quyền sửa đổi.",
  backMarketIntel: "Quay lại từ Trí tuệ thị trường",
  readOnlyMarketEvidence: "BẰNG CHỨNG THỊ TRƯỜNG CHỈ ĐỌC",
  marketIntelligence: "Trí tuệ thị trường",
  noActions: "KHÔNG THAO TÁC",
  marketIntelSafety:
    "Quan sát có chữ ký và ảnh chụp thị trường từ nhà cung cấp là bằng chứng, không phải hướng dẫn giao dịch. Màn hình này không thể ký, gửi, nhận phí hoặc chuyển tiền.",
  signals: "Tín hiệu",
  heatmap: "Bản đồ nhiệt",
  claims: "Nhận phí",
  selectMarketIntelTab: "Chọn chế độ trí tuệ thị trường {tab}",
  selectSignalWindow: "Chọn cửa sổ tín hiệu {window}",
  selectSignalType: "Lọc tín hiệu theo {type}",
  providerUnavailable: "không có nhà cung cấp",
  ingestion: "thu thập {status}",
  untracked: "không theo dõi",
  loadingSignals: "Đang tải sự kiện thị trường có chữ ký…",
  noSignalEvents: "Không có sự kiện có chữ ký trong cửa sổ này.",
  loadOlderSignals: "Tải bằng chứng tín hiệu cũ hơn",
  loadOlderEvidence: "Tải bằng chứng cũ hơn",
  openSignalToken: "Mở token tín hiệu {token}",
  sourceUnavailable: "không có nguồn",
  signatureUnavailable: "không có chữ ký",
  loadingHeatmap: "Đang tải bản đồ nhiệt thị trường đáng tin cậy…",
  heatmapInclusion: "{source} · gồm {included} · loại {excluded}",
  warnings: "Cảnh báo",
  lowLiquidity: "Thanh khoản thấp",
  incomplete: "Chưa đầy đủ",
  openHeatmapToken: "Mở {symbol}, {change}",
  noHeatmapRecords: "Không có bản ghi bản đồ nhiệt đáng tin cậy.",
  detected: "Phát hiện",
  firstClaims: "Lần nhận đầu",
  unpaidFake: "Chưa trả / giả",
  scanned: "Đã quét",
  scanningClaims: "Đang quét giao dịch PumpFees…",
  allClaims: "Tất cả lần nhận",
  unpaidClaims: "Lần nhận chưa trả",
  selectClaimFilter: "Lọc bằng chứng nhận phí theo {filter}",
  noClaimEvents: "Không có sự kiện nhận phí khớp bộ lọc.",
  claimBoundary:
    "Chỉ quan sát · không gọi hướng dẫn nhận phí, thao tác ví, gửi tin nhắn hay URL bên ngoài.",
  githubSocialFee: "Phí xã hội GitHub",
  socialFeeClaim: "Nhận phí xã hội",
  slot: "slot {slot}",
  amountUnparsed: "chưa phân tích số lượng",
  firstObservedClaim: "LẦN NHẬN ĐẦU QUAN SÁT ĐƯỢC",
  staleDegraded: "CŨ / SUY GIẢM",
  current: "HIỆN TẠI",
  backWalletIntel: "Quay lại từ Trí tuệ ví",
  publicAddressResearch: "NGHIÊN CỨU ĐỊA CHỈ CÔNG KHAI",
  walletIntelligence: "Trí tuệ ví",
  walletIntelSafety:
    "Tài sản ví công khai và PnL đã thực hiện được lập chỉ mục không chứng minh quyền sở hữu hoặc dự đoán lợi nhuận tương lai. Màn hình này không có thao tác theo dõi, sao chép, ký hoặc giao dịch.",
  smartMoney: "Dòng tiền thông minh",
  walletTracker: "Theo dõi ví",
  selectWalletIntelTab: "Chọn chế độ trí tuệ ví {tab}",
  loadingWalletRankings: "Đang tải xếp hạng ví từ nhà cung cấp hoặc chỉ mục…",
  rankingEvidence:
    "{source} · {quality} · {freshness} · xếp hạng là dữ liệu lịch sử",
  stale: "cũ",
  qualified: "Đủ điều kiện",
  historicalPnl: "PnL lịch sử",
  averageWinRate: "Tỷ lệ thắng TB",
  noSmartWallets:
    "Không có ví Smart Money hoặc Whale đáp ứng bằng chứng xếp hạng hiện tại.",
  inspectWallet: "Kiểm tra ví {badge} {address}",
  indexedTradesReliability:
    "{trades} giao dịch đã lập chỉ mục · độ tin cậy {reliability}",
  maxDrawdown: "Sụt giảm tối đa",
  bestObserved: "Tốt nhất quan sát",
  loadingTrackedWallets: "Đang tải ví theo dõi chỉ lưu trên thiết bị…",
  trackedWalletBoundary:
    "Nhãn và địa chỉ công khai chỉ lưu trên thiết bị · tối đa 50 · xác thực Solana đúng 32 byte",
  addPublicWallet: "Thêm ví công khai",
  trackedWalletAddress: "Địa chỉ ví theo dõi",
  trackedWalletLabel: "Nhãn ví theo dõi",
  solanaPublicAddress: "Địa chỉ Solana công khai",
  optionalLabel: "Nhãn (tùy chọn)",
  saveTrackedWallet: "Lưu ví theo dõi",
  saveWatchOnlyWallet: "Lưu ví chỉ theo dõi",
  exactSolanaKey: "Địa chỉ phải là khóa Solana base58 đúng 32 byte.",
  couldNotSaveWallet: "Không thể lưu ví.",
  noTrackedWallets: "Không có ví công khai nào được lưu trên thiết bị này.",
  inspectTrackedWallet: "Kiểm tra ví theo dõi {label}",
  removeTrackedWallet: "Xóa ví theo dõi {label}",
  loadingWalletEvidence: "Đang tải tài sản công khai và PnL đã lập chỉ mục…",
  walletEvidence: "Bằng chứng ví",
  tokenAccounts: "Tài khoản token",
  walletEvidenceLimitation:
    "Tài sản: tổng hợp Solana RPC ở máy chủ với giá DEX khả dụng; chỉ liệt kê phần đã làm giàu. PnL: {method} · không có PnL chưa thực hiện.",
  unpriced: "chưa định giá",
  backResearch: "Quay lại từ Không gian nghiên cứu",
  deviceOnlyResearch: "NGHIÊN CỨU CHỈ TRÊN THIẾT BỊ",
  researchWorkspace: "Không gian nghiên cứu",
  researchSafety:
    "Danh sách, ghi chú, ngưỡng và ô biểu đồ nằm trên thiết bị này. Giá và nến đến từ hợp đồng máy chủ đã xác thực. Ngưỡng chỉ là kiểm tra trực quan—không phải cảnh báo bền vững hay kích hoạt giao dịch.",
  snipeList: "Danh sách Snipe",
  multicharts: "Đa biểu đồ",
  selectResearchTab: "Chọn chế độ nghiên cứu {tab}",
  loadingResearch: "Đang tải không gian nghiên cứu trên thiết bị…",
  storageUnavailable:
    "Bộ nhớ thiết bị không khả dụng; thay đổi này có thể không được lưu.",
  deviceCandidates: "{count}/20 ứng viên chỉ trên thiết bị",
  snipeAddress: "Địa chỉ token Snipe",
  exactTokenMint: "Mint token Solana chính xác",
  addSnipe: "Thêm token vào Danh sách Snipe",
  addCandidate: "Thêm ứng viên nghiên cứu",
  exact32Bytes: "Địa chỉ phải giải mã thành đúng 32 byte.",
  noCandidatesResearch:
    "Chưa có ứng viên. Thêm mint token chính xác để bắt đầu nghiên cứu giá thật.",
  researchBoundary:
    "Để có quy tắc giá bền vững phía máy chủ và bằng chứng phân phối, hãy dùng cảnh báo Theo dõi với ví đã xác minh. Danh sách cục bộ này không tuyên bố theo dõi nền.",
  openTokenResearch: "Mở nghiên cứu token {symbol}",
  candidate: "ứng viên",
  removeSnipe: "Xóa ứng viên khỏi Danh sách Snipe",
  loadingTokenEvidence: "Đang tải bằng chứng token từ máy chủ…",
  tokenUnavailable: "Token không khả dụng",
  visualThresholdMet: "ĐẠT NGƯỠNG TRỰC QUAN KHI ĐANG MỞ · {direction}",
  above: "TRÊN",
  below: "DƯỚI",
  visualAboveUsd: "TRỰC QUAN TRÊN USD",
  visualBelowUsd: "TRỰC QUAN DƯỚI USD",
  visualAboveLabel: "Ngưỡng giá trực quan phía trên",
  visualBelowLabel: "Ngưỡng giá trực quan phía dưới",
  none: "Không có",
  candidateNotes: "Ghi chú nghiên cứu ứng viên",
  researchNotesPlaceholder: "Ghi chú nghiên cứu (chỉ trên thiết bị)",
  realChartsShared: "{count}/4 biểu đồ token thật · khung thời gian chung",
  selectChartTimeframe: "Chọn khung thời gian biểu đồ chung {timeframe}",
  multichartAddress: "Địa chỉ token đa biểu đồ",
  addExactMint: "Thêm mint token chính xác",
  addTokenChart: "Thêm biểu đồ token",
  noCharts:
    "Chưa cấu hình biểu đồ. Thêm tối đa bốn mint token chính xác; không chèn thị trường mặc định hoặc tổng hợp.",
  openChartToken: "Mở chi tiết token {symbol}",
  chartCandidate: "biểu đồ",
  refreshChart: "Làm mới biểu đồ token",
  removeChart: "Xóa biểu đồ token",
  loadingTokenIdentity: "Đang tải danh tính token…",
  loadingValidatedCandles: "Đang tải nến đã xác thực…",
  backOperations: "Quay lại từ Vận hành",
  readOnlyOperationalEvidence: "BẰNG CHỨNG VẬN HÀNH CHỈ ĐỌC",
  analyticsFeeds: "Phân tích & Nguồn dữ liệu",
  getOnly: "CHỈ GET",
  operationsSafety:
    "Phân tích thị trường tóm tắt các bản ghi nhà cung cấp quan sát được. Dữ liệu nguồn chỉ quan sát bằng chứng thời gian chạy và lưu trữ; không kích hoạt thăm dò, đổi nhà cung cấp, phát lại sự kiện hoặc lộ thông tin xác thực.",
  analytics: "Phân tích",
  feedData: "Dữ liệu nguồn",
  selectOperationsTab: "Chọn chế độ vận hành {tab}",
  loadingAnalytics: "Đang tải phân tích Solana trực tiếp…",
  operationsEvidence:
    "{source} · {quality} · {included} bản ghi mint chính xác · loại {excluded}",
  qualityUnavailable: "không có chất lượng",
  tracked: "Theo dõi",
  momentumLeaders: "Dẫn đầu động lượng",
  momentumDetail: "Thay đổi 1 giờ quan sát được; không phải dự đoán",
  noMomentum: "Không có bản ghi động lượng mint chính xác.",
  freshPairs: "Cặp mới",
  canonicalDedup: "Khử trùng lặp theo mint chuẩn",
  noFreshPairs: "Không có cặp mới với mint chính xác.",
  historicalTraderActivity: "Hoạt động nhà giao dịch lịch sử",
  thirtyDayObservation: "{source} · quan sát 30 ngày",
  indexedHistoricalWin:
    "{badge} · {trades} giao dịch đã lập chỉ mục · tỷ lệ thắng lịch sử {winRate}%",
  analyticsBoundary:
    "Tổng hợp chỉ dùng danh tính token chuẩn do máy chủ trả về. Không suy diễn số giao dịch, giá vốn hoặc tuyên bố dự đoán còn thiếu.",
  loadingFeedEvidence: "Đang tải bằng chứng nguồn dữ liệu quan sát…",
  feedEvidence: "{scope} · tạo {age} · {receiving} đang nhận",
  healthy: "Khỏe mạnh",
  unhealthy: "Không khỏe",
  receiving: "Đang nhận",
  runtimeQuality: "Chất lượng thời gian chạy",
  recoveryDrilldown: "Chi tiết phục hồi",
  runtimeCountersBoundary:
    "Bộ đếm backend tích lũy · chênh lệch xuất hiện sau lần làm mới tiếp theo",
  decodePipeline: "Quy trình giải mã đã quan sát",
  decodePipelineState: "Chất lượng {quality} · hồi phục {cooldown}",
  feedCounter_received: "Đã nhận",
  feedCounter_decoded: "Đã giải mã",
  feedCounter_persisted: "Đã lưu",
  feedCounter_dropped: "Đã loại",
  feedCounter_ignored: "Đã bỏ qua",
  deltaSinceRefresh: "Chênh lệch từ lần làm mới thành công trước",
  awaitingCounterBaseline: "Chờ lần làm mới tiếp theo để tính chênh lệch",
  runtimeCountersUnavailable: "Không có bộ đếm giải mã thời gian chạy.",
  eventPersistencePipeline: "Quy trình lưu sự kiện",
  eventBusCounters:
    "Đã phát {published} · đã lưu {persisted} · loại trùng {duplicate} · loại thời gian lỗi {invalid}",
  persistencePressure:
    "Lỗi lưu {failed} · loại do áp lực {dropped} · đang chờ {pending}",
  noRuntimeEvent: "Không có dấu thời gian sự kiện thời gian chạy.",
  degradedEvidence: "bằng chứng suy giảm",
  noReportedDegradation: "không báo cáo suy giảm",
  persistenceEvidence: "Bằng chứng lưu trữ: {status}",
  observabilityEvidence: "Bằng chứng quan sát: {status}",
  replayEvidence: "Bằng chứng phát lại: {status}",
  realtimeTimestamp: "Dấu thời gian trực tiếp: {timestamp}",
  validUnavailable: "hợp lệ, không có",
  invalidUnavailable: "không hợp lệ / không có",
  providerInventory: "Danh mục nhà cung cấp",
  configurationNotDelivery: "Cấu hình không chứng minh phân phối trực tiếp",
  noFeedInventory: "Không có bằng chứng danh mục nguồn dữ liệu.",
  recentIngestionJobs: "Tác vụ thu thập gần đây",
  durableNoControls: "Kết quả tác vụ bền vững; không có điều khiển",
  jobOutcome: "{processed} thành công · {failed} thất bại",
  noIngestionJobs: "Không nhận được tác vụ thu thập bền vững.",
  feedBoundary:
    "Tóm tắt chỉ đọc. URL điểm cuối, bản ghi mẫu, khóa nhà cung cấp, thăm dò chủ động, điều khiển phát lại và thay đổi bộ lập lịch đều cố ý vắng mặt.",
  persistedRecordsLabel: "{label}, {health}, {count} bản ghi đã lưu",
  connectionMeta: "{method} · {delivery} · {configuration}",
  subscriptionEvidence:
    "Kết nối {connected} · đăng ký {count} · đang nhận {receiving}",
  lastRuntimeSuccess: "Thành công gần nhất: {age}",
  lastRuntimeError: "Lỗi thời gian chạy gần nhất: {error}",
  rateLimitEvidence:
    "Yêu cầu {requests} · giới hạn {limited} · chờ {queued} · hồi phục {cooldown}",
  notApplicable: "không áp dụng",
  configured: "đã cấu hình",
  notConfigured: "chưa cấu hình",
  pairsCount: "{count} cặp",
  transactionsCount: "{count} giao dịch",
  candlesCount: "{count} nến",
  freshnessUnavailable: "không có độ mới",
  noPersistedObservation: "không có quan sát đã lưu",
  timeUnavailable: "không có thời gian",
  secondsAgo: "{count} giây trước",
  minutesAgo: "{count} phút trước",
  hoursAgo: "{count} giờ trước",
  openAnalytics: "Mở phân tích {symbol}",
  liquidityVolume: "TK {liquidity} · KL {volume} · {dex}",
  check: "KIỂM TRA",
};
const translations = { en, vi };
function interpolate(
  template: string,
  values?: Record<string, string | number>,
) {
  return values
    ? template.replace(/\{(\w+)\}/g, (match, key: string) =>
        key in values ? String(values[key]) : match,
      )
    : template;
}
const Context = createContext<SettingsContext | null>(null);

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [settings, setSettings] = useState(defaults);
  const [ready, setReady] = useState(false);
  useEffect(() => {
    void AsyncStorage.getItem(KEY)
      .then((raw) => {
        try {
          const value = JSON.parse(raw ?? "{}") as Partial<Settings>;
          setSettings({
            language: value.language === "vi" ? "vi" : "en",
            reduceMotion: value.reduceMotion === true,
            diagnosticTelemetry: value.diagnosticTelemetry === true,
          });
        } catch {
          setSettings(defaults);
        }
      })
      .finally(() => setReady(true));
  }, []);
  const update = useCallback(async (next: Settings) => {
    setSettings(next);
    await AsyncStorage.setItem(KEY, JSON.stringify(next));
  }, []);
  const value = useMemo<SettingsContext>(
    () => ({
      ...settings,
      ready,
      setLanguage: async (language) => update({ ...settings, language }),
      setReduceMotion: async (reduceMotion) =>
        update({ ...settings, reduceMotion }),
      setDiagnosticTelemetry: async (diagnosticTelemetry) =>
        update({ ...settings, diagnosticTelemetry }),
      resetPreferences: async () => {
        await AsyncStorage.removeItem(KEY);
        setSettings(defaults);
      },
      t: (key, values) =>
        interpolate(translations[settings.language][key], values),
    }),
    [settings, ready, update],
  );
  return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useSettings() {
  const value = useContext(Context);
  if (!value) throw new Error("useSettings must be inside SettingsProvider");
  return value;
}
export const SETTINGS_STORAGE_KEY = KEY;
