import AsyncStorage from '@react-native-async-storage/async-storage';
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Language = 'en' | 'vi';
type Settings = { language: Language; reduceMotion: boolean; diagnosticTelemetry: boolean };
type SettingsContext = Settings & { ready: boolean; setLanguage: (value: Language) => Promise<void>; setReduceMotion: (value: boolean) => Promise<void>; setDiagnosticTelemetry: (value: boolean) => Promise<void>; resetPreferences: () => Promise<void>; t: (key: TranslationKey, values?: Record<string, string | number>) => string };
const KEY = 'terminal-dex:settings:v1';
const defaults: Settings = { language: 'en', reduceMotion: false, diagnosticTelemetry: false };
const en = {
  discover: 'Discover', trenches: 'Trenches', monitor: 'Monitor', portfolio: 'Portfolio', more: 'More', moreTools: 'More tools', settings: 'Settings', privacySecurity: 'Privacy & security',
  realData: 'REAL DATA', searchTokens: 'Search live tokens or mint', clearSearch: 'Clear token search', trending: 'Trending', gainers: 'Gainers', losers: 'Losers', volume: 'Volume', newPairs: 'New Pairs', hotSearches: 'Hot Searches', surge: 'Surge', pumpLive: 'Pump Live', watchlist: 'Watchlist', filter: 'Filter', openFilters: 'Open market filters', searching: 'Searching', marketFeed: 'Market feed', searchingSources: 'Searching real market sources…', loadingMarkets: 'Loading live markets…', marketUnavailable: 'Market data unavailable', retry: 'Retry', watchlistEmpty: 'Your watchlist is empty', noMatchingTokens: 'No matching tokens', watchlistHint: 'Star tokens from any Discovery list to keep them here.', filtersHint: 'Adjust filters, search, or choose another market window.', marketFilters: 'Market filters', closeFilters: 'Close market filters', all: 'All', minLiquidity: 'Minimum liquidity (USD)', minMarketCap: 'Minimum market cap (USD)', reset: 'Reset', applyFilters: 'Apply filters', selectMode: 'Select {mode} market list', selectPeriod: 'Select {period} market period', selectDex: 'Select {dex} DEX',
  nextBc: 'NextBC',
  offlineBanner: 'Offline · showing only already loaded evidence. Requests and automatic refresh are paused.', recoveredBanner: 'Connection restored · refreshing active evidence.',
  liveLaunches: 'LIVE LAUNCHES', new: 'New', almostBonded: 'Almost bonded', migrated: 'Migrated', source: 'Source', loading: 'loading', launchFeed: 'provider-backed launch feed', loadingLaunches: 'Loading real launch feeds…', noLaunches: 'No verified {lane} tokens are available.', openLaunch: 'Open {symbol} launch details', reviewQuoteLabel: 'Review {symbol} quote', bondingProgress: 'Bonding progress', marketCap: 'MCap', liquidity: 'Liquidity', hourVolume: '1h volume', buysSells: '5m B/S', reviewQuote: 'Review quote', unknown: 'unknown', unavailable: 'unavailable',
  routesNote: 'Routes activate only after their real contracts and security checks are implemented.', openSettings: 'Open Settings', intelligenceAutomation: 'INTELLIGENCE & AUTOMATION', automationWarning: 'CopyTrade saves paused strategies. AI recommendations remain advisory and paper-only.', available: 'available', queued: 'queued', open: 'OPEN',
  deviceControls: 'DEVICE CONTROLS', backSettings: 'Back from Settings', language: 'Language / Ngôn ngữ', languageDescription: 'All primary tabs update immediately. Market symbols and provider evidence remain untranslated to preserve exact meaning.', accessibility: 'Accessibility', accessibilityDescription: 'Terminal DEX respects operating-system font scaling and screen readers. Controls expose roles, state, labels, and selected or disabled status.', reduceMotion: 'Reduce motion', reduceMotionDetail: 'Disables optional motion; live market refresh remains enabled.', telemetryDescription: 'Diagnostic telemetry is disabled by default. If enabled later, bounded payloads pass credential, signature, and address redaction before transport.', diagnosticTelemetry: 'Diagnostic telemetry', noTelemetry: 'No telemetry transport is configured in this build.', transportSecurity: 'Production API traffic requires HTTPS. iOS arbitrary loads and Android cleartext traffic are disabled.', deepLinkSecurity: 'Deep-link token addresses must decode to exactly 32 bytes; embedded snapshots are capped at 12 KB and must match the route.', walletSecurity: 'Verified wallet metadata stays in device-only secure storage and re-locks after backgrounding.', dataControls: 'Data controls', dataControlsDescription: 'Reset affects this installation only. Durable alerts, CopyTrade strategies, and other server-owned data require their own authenticated deletion flows.', clearQuestion: 'Clear private and local data?', clearDescription: 'This disconnects the wallet, revokes the app session, and removes local addresses, watchlists, filters, research, and preferences. Server-owned records are not deleted.', cancel: 'Cancel', clearLocalData: 'Clear local data', clearing: 'Clearing…', disconnectClear: 'Disconnect and clear local data', footerSecurity: 'Terminal DEX Mobile 0.1.0 · non-custodial · no secret keys stored',
  observationDesk: 'OBSERVATION DESK', live: 'Live', rules: 'Rules', delivery: 'Delivery', connecting: 'CONNECTING', selectMonitorView: 'Select {view} monitor view', loadingActivity: 'Loading observed Solana activity…', noActivity: 'No indexed on-chain observations are currently available. This feed does not synthesize activity.', signedObservations: '{count} signed observations · refresh 30s',
  portfolioLocked: 'Portfolio locked', portfolioLockedHint: 'Re-authenticate with biometrics or your device credential before showing the verified wallet.', unlocking: 'Unlocking…', unlockPortfolio: 'Unlock portfolio', revokeSession: 'Revoke session', ownershipVerified: 'OWNERSHIP VERIFIED', connectSecurely: 'Connect securely', walletSafety: 'Terminal DEX never requests or stores seed phrases. Android uses Mobile Wallet Adapter to sign a non-transaction ownership challenge.', openingWallet: 'Opening wallet…', connectVerify: 'Connect & verify wallet', orWatchOnly: 'OR WATCH ONLY', watchAddress: 'Watch-only wallet address', walletPlaceholder: 'Solana wallet address', loadWatchWallet: 'Load watch-only wallet', load: 'Load', watchOnlyHint: 'Watch-only addresses are public data and do not prove ownership.', verifiedWallet: 'VERIFIED WALLET', disconnectRevoke: 'Disconnect & revoke', watchOnly: 'WATCH ONLY', remove: 'Remove', loadingHoldings: 'Loading provider-backed holdings…', portfolioValue: 'Portfolio value', tokens: 'Tokens', weightedRisk: 'Weighted risk', allocation: 'Allocation', noPricedHoldings: 'No priced holdings were returned.', holdings: 'Holdings', pnlEvidence: 'PnL evidence', status: 'Status', realizedPnl: 'Realized PnL', unrealizedPnl: 'Unrealized PnL', indexedSwaps: 'Indexed swaps', connectPortfolioHint: 'Connect a wallet or load a watch-only address to view real holdings.',
} as const;
type TranslationKey = keyof typeof en;
const vi: { [K in TranslationKey]: string } = {
  discover: 'Khám phá', trenches: 'Token mới', monitor: 'Theo dõi', portfolio: 'Danh mục', more: 'Thêm', moreTools: 'Công cụ khác', settings: 'Cài đặt', privacySecurity: 'Quyền riêng tư & bảo mật',
  realData: 'DỮ LIỆU THẬT', searchTokens: 'Tìm token trực tiếp hoặc địa chỉ mint', clearSearch: 'Xóa tìm kiếm token', trending: 'Xu hướng', gainers: 'Tăng giá', losers: 'Giảm giá', volume: 'Khối lượng', newPairs: 'Cặp mới', hotSearches: 'Tìm kiếm nóng', surge: 'Bứt phá', pumpLive: 'Pump trực tiếp', watchlist: 'Theo dõi', filter: 'Bộ lọc', openFilters: 'Mở bộ lọc thị trường', searching: 'Đang tìm', marketFeed: 'Nguồn thị trường', searchingSources: 'Đang tìm nguồn thị trường thật…', loadingMarkets: 'Đang tải thị trường trực tiếp…', marketUnavailable: 'Không có dữ liệu thị trường', retry: 'Thử lại', watchlistEmpty: 'Danh sách theo dõi đang trống', noMatchingTokens: 'Không có token phù hợp', watchlistHint: 'Đánh dấu token từ danh sách Khám phá để lưu tại đây.', filtersHint: 'Điều chỉnh bộ lọc, tìm kiếm hoặc chọn khung thị trường khác.', marketFilters: 'Bộ lọc thị trường', closeFilters: 'Đóng bộ lọc thị trường', all: 'Tất cả', minLiquidity: 'Thanh khoản tối thiểu (USD)', minMarketCap: 'Vốn hóa tối thiểu (USD)', reset: 'Đặt lại', applyFilters: 'Áp dụng bộ lọc', selectMode: 'Chọn danh sách thị trường {mode}', selectPeriod: 'Chọn khung thị trường {period}', selectDex: 'Chọn DEX {dex}',
  nextBc: 'Sắp bonding',
  offlineBanner: 'Ngoại tuyến · chỉ hiển thị bằng chứng đã tải. Yêu cầu và làm mới tự động đang tạm dừng.', recoveredBanner: 'Đã kết nối lại · đang làm mới bằng chứng đang hoạt động.',
  liveLaunches: 'TOKEN RA MẮT TRỰC TIẾP', new: 'Mới', almostBonded: 'Gần hoàn tất', migrated: 'Đã chuyển', source: 'Nguồn', loading: 'đang tải', launchFeed: 'nguồn token mới từ nhà cung cấp', loadingLaunches: 'Đang tải nguồn token mới thật…', noLaunches: 'Không có token {lane} đã xác minh.', openLaunch: 'Mở chi tiết token mới {symbol}', reviewQuoteLabel: 'Xem báo giá {symbol}', bondingProgress: 'Tiến độ bonding', marketCap: 'Vốn hóa', liquidity: 'Thanh khoản', hourVolume: 'KL 1 giờ', buysSells: 'Mua/Bán 5 phút', reviewQuote: 'Xem báo giá', unknown: 'không rõ', unavailable: 'không có',
  routesNote: 'Chỉ mở chức năng sau khi hợp đồng dữ liệu thật và kiểm tra bảo mật đã hoàn tất.', openSettings: 'Mở Cài đặt', intelligenceAutomation: 'TRÍ TUỆ & TỰ ĐỘNG HÓA', automationWarning: 'CopyTrade chỉ lưu chiến lược tạm dừng. Khuyến nghị AI chỉ mang tính tham khảo và mô phỏng.', available: 'khả dụng', queued: 'đang chờ', open: 'MỞ',
  deviceControls: 'ĐIỀU KHIỂN THIẾT BỊ', backSettings: 'Quay lại từ Cài đặt', language: 'Ngôn ngữ / Language', languageDescription: 'Tất cả tab chính cập nhật ngay. Ký hiệu thị trường và bằng chứng nhà cung cấp giữ nguyên để bảo toàn ý nghĩa chính xác.', accessibility: 'Trợ năng', accessibilityDescription: 'Terminal DEX tôn trọng cỡ chữ và trình đọc màn hình của hệ điều hành. Điều khiển có vai trò, trạng thái, nhãn và trạng thái chọn hoặc vô hiệu hóa.', reduceMotion: 'Giảm chuyển động', reduceMotionDetail: 'Tắt chuyển động tùy chọn; làm mới thị trường trực tiếp vẫn hoạt động.', telemetryDescription: 'Chẩn đoán bị tắt mặc định. Nếu bật sau này, dữ liệu giới hạn được xóa thông tin xác thực, chữ ký và địa chỉ trước khi truyền.', diagnosticTelemetry: 'Chẩn đoán từ xa', noTelemetry: 'Bản dựng này không cấu hình kênh chẩn đoán.', transportSecurity: 'API sản xuất bắt buộc HTTPS. iOS không cho tải tùy ý và Android chặn lưu lượng văn bản rõ.', deepLinkSecurity: 'Địa chỉ token trong liên kết sâu phải giải mã đúng 32 byte; snapshot giới hạn 12 KB và phải khớp tuyến.', walletSecurity: 'Siêu dữ liệu ví đã xác minh ở bộ nhớ bảo mật trên thiết bị và tự khóa lại khi ứng dụng chạy nền.', dataControls: 'Điều khiển dữ liệu', dataControlsDescription: 'Đặt lại chỉ ảnh hưởng bản cài này. Cảnh báo, chiến lược CopyTrade và dữ liệu máy chủ cần luồng xóa đã xác thực riêng.', clearQuestion: 'Xóa dữ liệu riêng tư và cục bộ?', clearDescription: 'Thao tác này ngắt ví, thu hồi phiên và xóa địa chỉ, danh sách theo dõi, bộ lọc, nghiên cứu và tùy chọn cục bộ. Dữ liệu máy chủ không bị xóa.', cancel: 'Hủy', clearLocalData: 'Xóa dữ liệu cục bộ', clearing: 'Đang xóa…', disconnectClear: 'Ngắt kết nối và xóa dữ liệu cục bộ', footerSecurity: 'Terminal DEX Mobile 0.1.0 · không lưu ký · không lưu khóa bí mật',
  observationDesk: 'BÀN QUAN SÁT', live: 'Trực tiếp', rules: 'Quy tắc', delivery: 'Phân phối', connecting: 'ĐANG KẾT NỐI', selectMonitorView: 'Chọn chế độ theo dõi {view}', loadingActivity: 'Đang tải hoạt động Solana quan sát được…', noActivity: 'Hiện không có quan sát on-chain đã lập chỉ mục. Nguồn này không tạo dữ liệu giả.', signedObservations: '{count} quan sát có chữ ký · làm mới 30 giây',
  portfolioLocked: 'Danh mục đã khóa', portfolioLockedHint: 'Xác thực lại bằng sinh trắc học hoặc thông tin thiết bị trước khi hiển thị ví đã xác minh.', unlocking: 'Đang mở khóa…', unlockPortfolio: 'Mở khóa danh mục', revokeSession: 'Thu hồi phiên', ownershipVerified: 'ĐÃ XÁC MINH QUYỀN SỞ HỮU', connectSecurely: 'Kết nối an toàn', walletSafety: 'Terminal DEX không yêu cầu hoặc lưu cụm từ khôi phục. Android dùng Mobile Wallet Adapter để ký thử thách sở hữu không phải giao dịch.', openingWallet: 'Đang mở ví…', connectVerify: 'Kết nối và xác minh ví', orWatchOnly: 'HOẶC CHỈ THEO DÕI', watchAddress: 'Địa chỉ ví chỉ theo dõi', walletPlaceholder: 'Địa chỉ ví Solana', loadWatchWallet: 'Tải ví chỉ theo dõi', load: 'Tải', watchOnlyHint: 'Địa chỉ chỉ theo dõi là dữ liệu công khai và không chứng minh quyền sở hữu.', verifiedWallet: 'VÍ ĐÃ XÁC MINH', disconnectRevoke: 'Ngắt kết nối và thu hồi', watchOnly: 'CHỈ THEO DÕI', remove: 'Xóa', loadingHoldings: 'Đang tải tài sản từ nhà cung cấp…', portfolioValue: 'Giá trị danh mục', tokens: 'Token', weightedRisk: 'Rủi ro trọng số', allocation: 'Phân bổ', noPricedHoldings: 'Không có tài sản định giá được trả về.', holdings: 'Tài sản', pnlEvidence: 'Bằng chứng PnL', status: 'Trạng thái', realizedPnl: 'PnL đã thực hiện', unrealizedPnl: 'PnL chưa thực hiện', indexedSwaps: 'Swap đã lập chỉ mục', connectPortfolioHint: 'Kết nối ví hoặc tải địa chỉ chỉ theo dõi để xem tài sản thật.',
};
const translations = { en, vi };
function interpolate(template: string, values?: Record<string, string | number>) { return values ? template.replace(/\{(\w+)\}/g, (match, key: string) => key in values ? String(values[key]) : match) : template; }
const Context = createContext<SettingsContext | null>(null);

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [settings, setSettings] = useState(defaults); const [ready, setReady] = useState(false);
  useEffect(() => { void AsyncStorage.getItem(KEY).then((raw) => { try { const value = JSON.parse(raw ?? '{}') as Partial<Settings>; setSettings({ language: value.language === 'vi' ? 'vi' : 'en', reduceMotion: value.reduceMotion === true, diagnosticTelemetry: value.diagnosticTelemetry === true }); } catch { setSettings(defaults); } }).finally(() => setReady(true)); }, []);
  const update = useCallback(async (next: Settings) => { setSettings(next); await AsyncStorage.setItem(KEY, JSON.stringify(next)); }, []);
  const value = useMemo<SettingsContext>(() => ({ ...settings, ready, setLanguage: async (language) => update({ ...settings, language }), setReduceMotion: async (reduceMotion) => update({ ...settings, reduceMotion }), setDiagnosticTelemetry: async (diagnosticTelemetry) => update({ ...settings, diagnosticTelemetry }), resetPreferences: async () => { await AsyncStorage.removeItem(KEY); setSettings(defaults); }, t: (key, values) => interpolate(translations[settings.language][key], values) }), [settings, ready, update]);
  return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useSettings() { const value = useContext(Context); if (!value) throw new Error('useSettings must be inside SettingsProvider'); return value; }
export const SETTINGS_STORAGE_KEY = KEY;
